<h1><center>Laboratorio 8: El Multiverso Porteño 🦸</center></h1>

<center><strong>IA7202: Laboratorio de Programación Científica para Ciencia de Datos</strong></center>

---

### Cuerpo Docente

- Profesores: Pablo Badilla e Ignacio Núñez
- Auxiliar: Sofía Chávez
- Ayudantes: Javiera Arévalo, Tamara Cornejo, Ignacio Reyes

### Equipo

- Nombre de estudiante 1: Vicente Anguita
- Nombre de estudiante 2: Vicente Carrasco

---

<!-- DEFINICIÓN -->
<div style="padding:16px 20px; margin:16px 0; border-left:4px solid #3fb950; background:rgba(63,185,80,.12); color:inherit; border-radius:4px;">

  <strong style="display:block; margin-bottom:8px;">📖 Aprendizaje automático y sus tres familias</strong>

  El <strong>aprendizaje automático</strong> (<em>machine learning</em>, ML) construye modelos que aprenden patrones a partir de datos, en vez de programar las reglas a mano. Según qué información tiene el modelo para aprender, se distinguen tres familias:

  <ul>
  <li><strong>Supervisado</strong>: cada ejemplo trae la respuesta correcta, la <strong>etiqueta</strong>, y el modelo aprende a predecirla en ejemplos nuevos. Si la etiqueta es una categoría (spam o no spam) hablamos de <strong>clasificación</strong>; si es un número (el precio de un departamento), de <strong>regresión</strong>. Para medir cuánto acierta, los datos se separan en <strong>entrenamiento</strong>, con que aprende, y <strong>prueba</strong>, que el modelo nunca vio.</li>
  <li><strong>No supervisado</strong>: no hay etiquetas. El objetivo es encontrar estructura en los datos: qué observaciones se parecen, qué grupos aparecen, en qué direcciones varían. Por ejemplo, agrupar a los clientes de un supermercado según lo que compran, sin categorías definidas de antemano.</li>
  <li><strong>Por refuerzo</strong>: un agente toma decisiones en un entorno y recibe recompensas o castigos por ellas. Aprende una estrategia que maximiza la recompensa acumulada, como un programa que aprende a jugar ajedrez jugando partidas.</li>
  </ul>

```mermaid
flowchart TD
    ML["Aprendizaje automático"] --> S["Supervisado<br/>datos con etiqueta → predecir la etiqueta"]
    ML --> N["No supervisado<br/>datos sin etiqueta → encontrar estructura"]
    ML --> R["Por refuerzo<br/>acciones y recompensas → aprender una estrategia"]
```

</div>

### Reglas

- Trabajar en equipos de hasta dos personas.
- Este laboratorio es **solo no supervisado**: no hay una columna con la respuesta correcta que un modelo aprenda a predecir. Por eso no entrenen clasificadores ni regresores, no separen datos en entrenamiento y prueba y no midan aciertos contra `alignment` (bueno, malo o neutral). Esa columna y `creator` sirven para describir resultados, no para evaluarlos.
- Mantener las transformaciones de tablas en Polars, y el escalamiento, la codificación y la reducción de dimensión en scikit-learn. No usar `pandas` ni ciclos `for` o `while` para transformar filas; sí pueden usar un `for` para repetir un experimento con distintos parámetros, como el número de grupos o la semilla aleatoria. La única conversión a pandas es la de la 1.1, para entregarle el catálogo a fg-data-profiling, que no acepta DataFrames de Polars.
- No modificar los archivos de `data/raw/`.

### Flujo de trabajo

El notebook sirve para explorar y decidir. Lo que la evidencia justifica se traslada a `src/heroverse/`, y las pruebas entregadas indican cuándo una etapa está cerrada:

```bash
uv run pytest -m etapa1
uv run pytest -m etapa2
uv run pytest -m etapa3
uv run pytest -m etapa5
```

La etapa 4 no tiene pruebas: se comprueba mirando las proyecciones, como indica su recuadro.

<!-- IMPORTANTE -->
<div style="padding:16px 20px; margin:16px 0; border-left:4px solid #8957e5; background:rgba(137,87,229,.12); color:inherit; border-radius:4px;">

  <strong style="display:block; margin-bottom:8px;">📌 Instalar antes de la sesión</strong>
  Abran una terminal en la raíz de este laboratorio y ejecuten el comando de abajo, que instala todo lo que usa el laboratorio.

  <table>
    <thead>
      <tr><th>Paquete</th><th>Para qué lo usamos</th><th>Etapa</th></tr>
    </thead>
    <tbody>
      <tr><td><code>fg-data-profiling</code></td><td>Reporte de EDA del catálogo</td><td>1</td></tr>
      <tr><td><code>polars</code>, <code>pyarrow</code></td><td>Lectura y transformación de tablas; <code>pyarrow</code> permite el <code>.to_pandas()</code> del reporte</td><td>Todas</td></tr>
      <tr><td><code>scikit-learn</code>, <code>scipy</code></td><td>Escaladores, encoders, pipelines, TF-IDF, PCA y clustering; matrices sparse</td><td>1–5</td></tr>
      <tr><td><code>umap-learn</code></td><td>Proyecciones UMAP</td><td>4</td></tr>
      <tr><td><code>plotly</code></td><td>Gráficos interactivos</td><td>1–5</td></tr>
      <tr><td><code>jupyterlab</code></td><td>Entorno de notebooks</td><td>Todas</td></tr>
    </tbody>
  </table>
</div>

```bash
uv sync --locked --all-groups
```

## Contexto

<!-- LORE -->
<div style="padding:16px 20px; margin:16px 0; border-left:4px solid #0f9e99; background:rgba(15,158,153,.12); color:inherit; border-radius:4px;">

  <strong style="display:block; margin-bottom:8px;">📜 El encargo de la Magneta</strong>

  <div style="text-align: center; margin: 16px 0;">
    <img src="static/lore_1.jpeg" alt="Ilustración de cómic con decenas de personajes de Marvel y DC reunidos en una misma escena, entre ellos Superman, Batman, Wonder Woman, Wolverine, Hulk, Spider-Man y Tormenta." style="width: 600px; max-width: 100%; height: auto;">
  </div>
  
**Cerro Alegre Games** es un estudio de juegos de mesa que funciona en una antigua casona de Valparaíso. Su directora creativa, **Magda «Magneta» Lehnsherr**, está trabajando en <em>Multiverso Porteño</em>, un juego de cartas en el que cada carta representa a un personaje de cómic con sus propias características, fortalezas y habilidades.

Para diseñar el juego sin inventar estadísticas a mano, la Magneta descargó el catálogo completo de superherodb: 1 367 personajes pertenecientes a distintas editoriales, junto con información sobre sus puntajes, características físicas, poderes y descripciones. La idea es aprovechar esos datos para tomar decisiones de diseño de forma sistemática.

Sin embargo, el proyecto enfrenta dos problemas.

El primero es económico. Licenciar personajes de Marvel cuesta más que todo el presupuesto disponible para imprimir el juego; el encargo permite candidatos de cualquier otra editorial, incluida DC. Por eso, cada vez que el equipo encuentra un personaje de Marvel que encaja perfectamente en una carta, necesita buscar un <strong>equivalente de otra editorial</strong>: alguien con características similares, poderes comparables y, en términos del juego, una forma de jugar parecida.

El segundo problema es de diseño. Un mazo interesante no debería estar compuesto por personajes prácticamente idénticos. Necesita variedad: personajes que destaquen por su fuerza, otros por su inteligencia, algunos por su resistencia y otros por combinaciones menos evidentes de atributos. En otras palabras, el equipo necesita identificar **arquetipos de personajes**. El problema es que nadie en Cerro Alegre Games quiere definirlos de antemano a partir de intuiciones o categorías arbitrarias. **La idea es que esos grupos emerjan directamente de los datos.**

Aunque parecen tareas distintas, ambas esconden la misma pregunta: **¿qué significa que dos personajes se parezcan?**

Responderla no es tan sencillo como comparar una sola estadística. Dos personajes podrían tener niveles de fuerza similares, pero capacidades intelectuales completamente distintas; compartir poderes, pero diferir mucho en resistencia; o parecerse en casi todo salvo en una característica cuya escala domina al resto.

La noción de similitud dependerá, por tanto, de **cómo representemos a cada personaje**, qué variables utilicemos y cómo hagamos comparables sus distintas escalas.

Eso es precisamente lo que construiremos en este laboratorio: una representación numérica de los personajes que nos permita explorar sus similitudes, encontrar alternativas comparables entre editoriales e identificar estructuras y arquetipos que aparecen naturalmente en los datos.


</div>

## Objetivos

- Generar features numéricas y binarias a partir de strings sucios, distinguiendo un dato faltante de un cero.
- Elegir un escalamiento según la distribución de cada feature y medir su efecto sobre los vecinos más cercanos.
- Codificar variables categóricas y componer un preprocesador que se ajusta una vez y se aplica a datos nuevos.
- Representar texto como bag of words y TF-IDF, y comparar los vecinos que entrega cada uno.
- Proyectar representaciones con PCA y UMAP sabiendo qué se puede y qué no se puede leer en ellas.
- Agrupar sin etiquetas y justificar los grupos con silhouette, estabilidad y perfiles interpretables.

### Temas a tratar

EDA con `fg-data-profiling`, feature engineering, escalamiento, encoding, `ColumnTransformer` y `Pipeline`, distancia de Jaccard, bag of words, TF-IDF, similitud coseno, PCA con loadings, UMAP, K-Means, silhouette y ARI. El año de aparición y DBSCAN quedan como extensiones opcionales.

### Evaluación

<!-- EVALUACIÓN -->
<div style="padding:16px 20px; margin:16px 0; border-left:4px solid #8b5cf6; background:rgba(139,92,246,.12); color:inherit; border-radius:4px;">

  <strong style="display:block; margin-bottom:8px;">📊 Distribución del puntaje</strong>

| Etapa | Evidencia | Puntaje |
| --- | --- | ---: |
| 1 | Auditoría 0,3; unidades 0,4; poderes 0,2; selección 0,1; features 0,2; pipelines numéricos 0,4; categorías 0,3; integración 0,3 | 2,2 |
| 2 | Predicción 0,1; vecinos 0,2; comparación de escalas 0,1; Jaccard 0,2; módulo 0,2 | 0,8 |
| 3 | Predicción 0,1; TF-IDF 0,3; bag of words 0,3; comparación 0,3; módulo 0,2 | 1,2 |
| 4 | PCA con loadings 0,4; UMAP 0,4 | 0,8 |
| 5 | Silhouette engañoso 0,2; arquetipos 0,3; acuerdo entre representaciones 0,2; módulo y entrega 0,3 | 1,0 |
| **Total** | | **6,0** |

  La nota se calcula como 1,0 + puntaje obtenido.
</div>

### Rutas del laboratorio

In [1]:
from pathlib import Path
import sys

RUTA_LAB = Path.cwd().parent
if str(RUTA_LAB) not in sys.path:
    sys.path.insert(0, str(RUTA_LAB))

RAW_DIR = Path("../data/raw")
FIGURES_DIR = Path("../reports/figures")

---
## Etapa 1 — Del catálogo a las representaciones tabulares (2,2 puntos)

<!-- LORE -->
<div style="padding:16px 20px; margin:16px 0; border-left:4px solid #0f9e99; background:rgba(15,158,153,.12); color:inherit; border-radius:4px;">

  <strong style="display:block; margin-bottom:8px;">📜 El multiverso del caos</strong>

  La Magneta quiso partir por algo sencillo: ordenar el catálogo por peso. Abrió la planilla, miró la columna correspondiente y descubrió rápidamente que los datos no estaban precisamente listos para cooperar.

  Algunas filas contienen valores como <code>"198 lb • 89 kg"</code>, otras registran <code>"6,600 lb • 3.0 tons"</code> y en varios casos aparece simplemente <code>"-"</code>. El problema no es solo de formato: distintas unidades, textos mezclados con números y datos ausentes hacen imposible comparar directamente a los personajes.

  Antes de calcular distancias, buscar equivalentes o descubrir arquetipos, el equipo necesita transformar esta información en valores numéricos consistentes. Eso implica decidir <strong>qué número extraer, en qué unidad representarlo y qué hacer cuando el dato no está disponible</strong>.

  En otras palabras, antes de analizar el multiverso, toca poner un poco de orden en él.
</div>

<!-- DEFINICIÓN -->
<div style="padding:16px 20px; margin:16px 0; border-left:4px solid #3fb950; background:rgba(63,185,80,.12); color:inherit; border-radius:4px;">

  <strong style="display:block; margin-bottom:8px;">📖 Features y representaciones</strong>
  Una <strong>feature</strong> es una característica medible o derivada. El <strong>feature engineering</strong> construye, transforma o selecciona esas variables: extraer una magnitud de un texto, unificar unidades, contar etiquetas o codificar categorías. Con $p$ features, cada observación se representa mediante un vector $x = (x_1, \ldots, x_p)$. Ese vector es la <strong>representación</strong> de la observación. Los algoritmos comparan esos vectores: las variables que elegimos y sus escalas determinan qué significa «parecido».
</div>

### 1.1 — Auditoría del catálogo y del lote nuevo (0,3 puntos)

Comenzamos leyendo el catálogo y dejamos que Polars infiera automáticamente el esquema, es decir, el nombre y el tipo de cada columna. El significado de cada columna está en `data/raw/README.md`; la primera, sin nombre, es un índice heredado que no identifica al personaje. Los seis puntajes (`intelligence_score`, `strength_score`, `speed_score`, `durability_score`, `power_score` y `combat_score`, de 0 a 100) se interpretan como `Int64`. `overall_score` es el puntaje global que publica la fuente. Los poderes todavía están en `superpowers`, una lista almacenada como texto; construiremos sus columnas binarias después. En cambio, columnas como `height`, `weight` y `overall_score` se mantienen como texto, ya que contienen una mezcla de valores numéricos, unidades y marcadores como `"-"`.

Esta primera lectura nos permite distinguir entre dos problemas diferentes: <strong>cómo están almacenados los datos</strong> y <strong>qué significan realmente sus valores</strong>. La inferencia de tipos solo puede decidir si una columna parece contener enteros, flotantes o texto; no conoce las convenciones utilizadas en el catálogo.

Por ejemplo, Polars no puede saber por sí solo que `"-"` representa un dato ausente, ni que un puntaje igual a `0` puede estar siendo utilizado con el mismo significado. Esa interpretación requiere revisar los datos y comprender su semántica antes de comenzar a transformarlos.

In [2]:
import polars as pl

catalogo = pl.read_csv(RAW_DIR / "catalogo.csv")
catalogo.select("name", "creator", "height", "weight", "strength_score").head()

name,creator,height,weight,strength_score
str,str,str,str,i64
"""3-D Man""","""Marvel Comics""","""-""","""-""",30
"""A-Bomb""","""Marvel Comics""","""6'8 • 203 cm""","""980 lb • 441 kg""",100
"""Aa""","""DC Comics""","""-""","""-""",50
"""Aaron Cash""","""DC Comics""","""-""","""-""",10
"""Aayla Secura""","""George Lucas""","""-""","""-""",40


<!-- DEFINICIÓN -->
<div style="padding:16px 20px; margin:16px 0; border-left:4px solid #3fb950; background:rgba(63,185,80,.12); color:inherit; border-radius:4px;">

  <strong style="display:block; margin-bottom:8px;">📖 Unidad de observación</strong>

  La <strong>unidad de observación</strong> es el objeto que representa cada fila de una tabla. Puede ser una persona, una venta, una medición, una película o, en este caso, una versión de un personaje de cómic: Batman (LEGO) y Batman (Arkham) son filas distintas, con atributos propios.

  Identificarla correctamente es uno de los primeros pasos de cualquier análisis, porque determina <strong>qué estamos contando, comparando y transformando</strong>. Antes de modificar una tabla conviene preguntarse: ¿qué representa exactamente una fila?, ¿qué columna permite identificarla de forma única? y ¿cuántas observaciones esperamos conservar después de cada transformación?

  Por ejemplo, si nuestra unidad de observación es una versión de un personaje, cada versión debería aparecer una sola vez. Si dos filas describen a la misma versión, no estamos incorporando una nueva observación, sino duplicando información existente.

  Esto puede parecer un detalle menor, pero tiene efectos concretos. Dos filas idénticas tendrán distancia cero entre sí y, además, ese personaje quedará <strong>sobrerrepresentado</strong>: contará dos veces al calcular promedios, distribuciones o agrupamientos. En otras palabras, una duplicación puede alterar la estructura aparente de los datos.

  Por eso, antes de construir features o calcular similitudes, conviene verificar que la tabla respete la unidad de observación que queremos estudiar.
</div>

Generemos un reporte con `fg-data-profiling`, que se importa como `data_profiling`. La conversión a pandas se usa solo para este reporte; las transformaciones siguen en Polars. `minimal=True` omite análisis costosos. Declaramos `height`, `weight`, `overall_score` y `superpowers` como categóricas para que el reporte muestre sus textos tal cual, incluido cuántas veces aparece `"-"`, en vez de intentar leerlos como números. Abran `reports/figures/eda_catalogo.html` en el navegador.

In [3]:
from data_profiling import ProfileReport

reporte = ProfileReport(
    catalogo.to_pandas(),
    title="Catálogo de superherodb",
    minimal=True,
    type_schema={
        "height": "categorical",
        "weight": "categorical",
        "overall_score": "categorical",
        "superpowers": "categorical",
    },
)
reporte.to_file(FIGURES_DIR / "eda_catalogo.html")

c:\Users\Asus\Laboratorio-de-Programaci-n-Cient-fica-para-Ciencia-de-DatosIA7202\labs\lab_8\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Export report to file: 100%|██████████| 1/1 [00:00<00:00, 27.28it/s]


<!-- DEFINICIÓN -->
<div style="padding:16px 20px; margin:16px 0; border-left:4px solid #3fb950; background:rgba(63,185,80,.12); color:inherit; border-radius:4px;">

  <strong style="display:block; margin-bottom:8px;">📖 Faltantes y valores centinela</strong>

  Un <strong>dato faltante</strong> indica que una medición o característica no está disponible. Sin embargo, algunas fuentes no lo representan con <code>null</code>, sino mediante <strong>valores centinela</strong> como <code>0</code>, <code>-1</code>, <code>"-"</code> o una lista vacía.

  El problema es que estos valores pueden parecer datos válidos. Si no los identificamos, un algoritmo los tratará literalmente: una altura desconocida codificada como <code>0</code> pasa a significar “0 cm” y puede alterar distancias, promedios o agrupamientos.

  Por eso, antes de analizar los datos debemos distinguir entre <strong>un valor real</strong> y <strong>un valor utilizado para representar ausencia de información</strong>.
</div>

Inspeccionen las versiones de Batman con `catalogo.filter(pl.col("name").str.contains("Batman")).select("name", "real_name", "creator")` y calculen la media y la desviación estándar de `intelligence_score` y `strength_score`. Las usarán en las preguntas 1 y 3.

In [4]:
batman = catalogo.filter(pl.col("name").str.contains("Batman")).select(
    "name", "real_name", "creator"
)
print(batman)

print(
    "Filas:", catalogo.height,
    "| name únicos:", catalogo["name"].n_unique(),
    "| name nulos:", catalogo["name"].null_count(),
)

resumen_puntajes = catalogo.select(
    pl.col("intelligence_score").mean().alias("intelligence_media"),
    pl.col("intelligence_score").std().alias("intelligence_sd"),
    pl.col("strength_score").mean().alias("strength_media"),
    pl.col("strength_score").std().alias("strength_sd"),
)
print(resumen_puntajes)

shape: (12, 3)
┌─────────────────────────────────┬────────────────┬───────────┐
│ name                            ┆ real_name      ┆ creator   │
│ ---                             ┆ ---            ┆ ---       │
│ str                             ┆ str            ┆ str       │
╞═════════════════════════════════╪════════════════╪═══════════╡
│ Batman (Arkham)                 ┆ Bruce Wayne    ┆ DC Comics │
│ Batman (Burtonverse)            ┆ Bruce Wayne    ┆ DC Comics │
│ Batman (DC One Million)         ┆ null           ┆ DC Comics │
│ Batman (DCAU)                   ┆ Bruce Wayne    ┆ DC Comics │
│ Batman (GAM)                    ┆ Kirk Langstrom ┆ DC Comics │
│ …                               ┆ …              ┆ …         │
│ Batman (LEGO)                   ┆ Bruce Wayne    ┆ Lego      │
│ Batman (The Brave And The Bold… ┆ Bruce Wayne    ┆ DC Comics │
│ Battle-Suit Batman (DCEU)       ┆ Bruce Wayne    ┆ DC Comics │
│ The Batman Of Zur-En-Arrh       ┆ Tlano          ┆ DC Comics │
│ Vampire 

<!-- PREGUNTA -->
<div style="padding:16px 20px; margin:16px 0; border-left:4px solid #58a6ff; background:rgba(88,166,255,.12); color:inherit; border-radius:4px;">

  <strong style="display:block; margin-bottom:8px;">❓ Auditoría</strong>
  1. ¿Qué representa una fila y qué evidencia confirma que `name` la identifica?
2. Que los puntajes sean numéricos y no tengan nulos, ¿significa que todas sus mediciones están disponibles? Justifiquen con un centinela del catálogo.
3. Con la media y la desviación estándar de `intelligence_score` y `strength_score`, ¿cuál está más dispersa y hacia dónde se concentran sus valores?
4. ¿Qué información describe `superpowers` y qué significa encontrar una lista vacía? ¿Podemos concluir que el personaje no tiene poderes?
5. ¿Qué puede revelar la cardinalidad de una columna, es decir, su número de valores distintos? Den un ejemplo del catálogo.
</div>

**1.** Cada fila es una versión de personaje: hay 1.367 nombres únicos, aunque varias versiones compartan identidad, como Batman.

**2.** No necesariamente. En 65 filas todos los puntajes son cero y `overall_score` es `"-"`: faltan datos, no capacidades.

**3.** Fuerza varía más que inteligencia (desviaciones cercanas a 34,6 y 25,1). Inteligencia se concentra en valores altos; fuerza está más dispersa.

**4.** `[]` indica que no hay poderes registrados, no que el personaje carezca de ellos.

**5.** La cardinalidad permite distinguir identificadores y categorías: `name` tiene 1.367 valores, `alignment` solo 3 y `type_race` 67.

La Magneta también recibió 84 personajes que llegaron después de la descarga del catálogo. Al final habrá que asignarles un arquetipo, así que tienen que pasar por la misma representación que el catálogo. Antes, hay que auditarlos.

Lean `nuevos.csv` imponiendo `catalogo.schema` con `schema_overrides`, en vez de dejar que Polars infiera un esquema propio: así, una columna que en el lote venga vacía no se lee con otro tipo que en el catálogo, y las dos tablas siguen siendo comparables. En `nuevos`, eliminen las filas idénticas en todas sus columnas y las que tienen `name` nulo, conservando el orden de primera aparición. Comprueben después que `name` es único y no nulo. Si dos filas distintas comparten `name`, deténganse y revísenlas en vez de elegir una al azar; en este lote no ocurre. Impriman cuántas filas llegaron (84) y cuántas quedan (81).

In [5]:
nuevos_brutos = pl.read_csv(
    RAW_DIR / "nuevos.csv",
    schema_overrides=catalogo.schema,
)
filas_llegaron = nuevos_brutos.height

nuevos = (
    nuevos_brutos
    .unique(maintain_order=True)
    .filter(pl.col("name").is_not_null())
)

if nuevos["name"].null_count() > 0 or nuevos["name"].n_unique() != nuevos.height:
    raise ValueError("El lote nuevo contiene name nulos o repetidos.")

print(f"Filas recibidas: {filas_llegaron}")
print(f"Filas después de depurar: {nuevos.height}")
nuevos.select("name", "creator", "height", "weight").head()

Filas recibidas: 84
Filas después de depurar: 81


name,creator,height,weight
str,str,str,str
"""514A (Gotham)""","""DC Comics""","""-""","""-"""
"""Ace Morgan""","""DC Comics""","""-""","""-"""
"""A'dal""","""Blizzard Entertainment""","""-""","""-"""
"""Agent Zero (FOX)""","""Marvel Comics""","""-""","""-"""
"""Ajax (FOX)""","""Marvel Comics""","""-""","""-"""


<!-- PREGUNTA -->
<div style="padding:16px 20px; margin:16px 0; border-left:4px solid #58a6ff; background:rgba(88,166,255,.12); color:inherit; border-radius:4px;">

  <strong style="display:block; margin-bottom:8px;">❓ Pregunta</strong>
  Más adelante, <code>construir_features</code> (1.5) exigirá que <code>name</code> sea único y no nulo.
  <ol>
  <li>¿Qué filas sacaron?</li>
  <li>¿Qué habría pasado al construir las features con el lote sin depurar?</li>
  </ol>
</div>

**1.** Se quitan tres filas: dos con nombre nulo y un Batcow duplicado. Quedan 81 de 84.

**2.** Sin esa limpieza, un personaje podría carecer de identificador o aparecer dos veces, rompiendo la correspondencia entre nombres y filas.

### 1.2 — Unidades y datos faltantes (0,4 puntos)

Ahora comenzaremos a transformar algunas columnas del catálogo en features numéricas utilizables.

Para eso debemos resolver dos problemas concretos: <strong>normalizar unidades</strong> y <strong>representar correctamente los datos faltantes</strong>. Alturas y pesos aparecen mezclando números, texto y distintas unidades, mientras que la ausencia de información puede estar codificada como <code>"-"</code>, <code>0</code> u otros valores especiales.

La idea será llevar cada magnitud a una unidad común y convertir los valores que realmente significan «sin dato» en <code>null</code>. Así, un número representará una medición conocida y no una ausencia disfrazada.

<!-- DEFINICIÓN -->
<div style="padding:16px 20px; margin:16px 0; border-left:4px solid #3fb950; background:rgba(63,185,80,.12); color:inherit; border-radius:4px;">

  <strong style="display:block; margin-bottom:8px;">📖 Extraer valores y normalizar unidades</strong>

  Cuando una columna mezcla números, texto y unidades, primero necesitamos <strong>separar la magnitud de su unidad</strong>. Para ello podemos usar <code>str.extract(patron, grupo)</code>, que recupera partes específicas de un texto mediante una <strong>expresión regular</strong>, un patrón que describe qué forma tiene el texto buscado. Cada par de paréntesis del patrón es un <strong>grupo de captura</strong>, numerado desde 1: en <code>r"([\d.]+) (kg|g)"</code>, el grupo 1 es el número (dígitos y puntos) y el grupo 2 la unidad. Si el patrón no calza, <code>extract</code> devuelve <code>null</code>.

  Una vez identificada la unidad, <code>pl.when(...).then(...).otherwise(...)</code> permite aplicar distintas conversiones según cada caso. Así podemos transformar representaciones diferentes de una misma magnitud a una <strong>unidad común</strong>.

  Veamos el mismo problema en una feria libre, donde los pesos vienen expresados en gramos o kilogramos.
</div>

In [6]:
feria = pl.DataFrame(
    {
        "producto": ["palta", "tomate", "cilantro"],
        "peso": ["1.5 kg", "800 g", "-"],
    }
)
valor = pl.col("peso").str.extract(r"([\d.]+) (kg|g)", 1)
unidad = pl.col("peso").str.extract(r"([\d.]+) (kg|g)", 2)
feria.with_columns(
    pl.when(unidad == "kg")
    .then(valor.cast(pl.Float64) * 1000)
    .otherwise(valor.cast(pl.Float64))
    .alias("peso_g")
)

producto,peso,peso_g
str,str,f64
"""palta""","""1.5 kg""",1500.0
"""tomate""","""800 g""",800.0
"""cilantro""","""-""",null


El cilantro queda con `null`, no con `0`: `"-"` no calza con el patrón, y así queda registrado que la feria no informó su peso, lo que es distinto de que no pese nada.

Ojo con los separadores. La feria usa punto decimal, igual que el catálogo, que viene en formato estadounidense. En el catálogo, además, la coma separa miles: `"6,600 lb"` son seis mil seiscientas libras, no 6,6.

Cuenten en el catálogo, con ayuda del EDA:

- [ ] cuántas filas contienen `"-"` en `height` y en `weight`;
- [ ] cuántos valores `0` aparecen en cada uno de los seis puntajes y cuántas veces aparece `"-"` en `overall_score`;
- [ ] cuántas filas tienen `superpowers == "[]"`, mostrando algunos de sus nombres para interpretar esa ausencia.

Hint: pueden utilizar operaciones de Polars como:

- `filter(...)` para inspeccionar las filas que cumplen una condición;
- `value_counts()` para revisar los valores más frecuentes de una columna;
- `null_count()` para contar valores `null`;
- comparaciones como `pl.col("columna") == valor`;
- `sum()` sobre expresiones booleanas para contar cuántas filas cumplen una condición.

Por ejemplo:

```python
catalogo.select(
    (pl.col("weight") == "-").sum().alias("peso_sin_dato"),
    pl.col("weight").null_count().alias("peso_null"),
)
```

La lista `PUNTAJES`, con los nombres de los seis puntajes, está en `src/heroverse/columns.py`. Ese archivo es material provisto: no hay que completar nada en él.

In [7]:
from src.heroverse.columns import PUNTAJES

In [8]:
print(
    catalogo.select(
        (pl.col("height") == "-").sum().alias("height_guion"),
        (pl.col("weight") == "-").sum().alias("weight_guion"),
        (pl.col("overall_score") == "-").sum().alias("overall_guion"),
    )
)

print(
    catalogo.select(
        *[(pl.col(c) == 0).sum().alias(f"{c}_ceros") for c in PUNTAJES]
    )
)

sin_ficha = pl.all_horizontal(*(pl.col(c) == 0 for c in PUNTAJES))
print("Filas con los seis puntajes en cero:", catalogo.filter(sin_ficha).height)
print(
    catalogo.filter(sin_ficha)
    .group_by("overall_score")
    .len()
    .sort("len", descending=True)
)

sin_poderes_registrados = catalogo.filter(pl.col("superpowers") == "[]")
print("Filas con superpowers == []:", sin_poderes_registrados.height)
print(sin_poderes_registrados.select("name", "creator", "superpowers").head(12))

shape: (1, 3)
┌──────────────┬──────────────┬───────────────┐
│ height_guion ┆ weight_guion ┆ overall_guion │
│ ---          ┆ ---          ┆ ---           │
│ u32          ┆ u32          ┆ u32           │
╞══════════════╪══════════════╪═══════════════╡
│ 307          ┆ 364          ┆ 102           │
└──────────────┴──────────────┴───────────────┘
shape: (1, 6)
┌────────────────┬────────────────┬────────────────┬───────────────┬───────────────┬───────────────┐
│ intelligence_s ┆ strength_score ┆ speed_score_ce ┆ durability_sc ┆ power_score_c ┆ combat_score_ │
│ core_ceros     ┆ _ceros         ┆ ros            ┆ ore_ceros     ┆ eros          ┆ ceros         │
│ ---            ┆ ---            ┆ ---            ┆ ---           ┆ ---           ┆ ---           │
│ u32            ┆ u32            ┆ u32            ┆ u32           ┆ u32           ┆ u32           │
╞════════════════╪════════════════╪════════════════╪═══════════════╪═══════════════╪═══════════════╡
│ 102            ┆ 110        

<!-- PREGUNTA -->
<div style="padding:16px 20px; margin:16px 0; border-left:4px solid #58a6ff; background:rgba(88,166,255,.12); color:inherit; border-radius:4px;">

  <strong style="display:block; margin-bottom:8px;">❓ Antes de transformar</strong>

1. Si los valores <code>"-"</code> de <code>weight</code> se transformaran en <code>0 kg</code>, ¿con qué tipo de personajes tenderían a quedar cerca esas observaciones al calcular distancias? ¿Por qué sería una similitud artificial?
2. Algunas filas registran <code>"0'0 • 0 cm"</code> en <code>height</code>, mientras que otras tienen los seis puntajes en <code>0</code>. Expliquen por qué una altura de 0 cm no es válida y revisen qué valor tiene <code>overall_score</code> en las filas con los seis puntajes en 0. ¿Qué tratamiento proponen para cada caso y con qué evidencia?
3. Entre las filas con <code>superpowers == "[]"</code> aparecen personajes como Alfred Pennyworth y Cecilia Reyes. Cuando pasemos los poderes a columnas de 0 y 1 (1.3), ¿qué interpretación debería tener su fila de ceros? ¿Qué limitación de esta representación conviene dejar explícita?
</div>

**1.** Un `"-"` en peso significa desconocido, no 0 kg. Poner cero crearía parecidos falsos con personajes livianos.

**2.** Una altura de 0 cm también es faltante. Los seis puntajes en cero a la vez coinciden con `overall_score = "-"`, por eso se anulan juntos; un cero aislado se mantiene.

**3.** Un vector de poderes en ceros significa que no se registraron etiquetas, aunque en realidad podría tener capacidades.

Construyan `medidas_exploradas` a partir de `catalogo`, conservando el orden de las 1 367 filas. La tabla debe tener, en este orden, `name`, `altura_cm` y `peso_kg` como `Float64` y los seis `PUNTAJES` con sus nombres originales.

- [ ] Extraer la parte métrica de `height` y `weight`, la que va después de `•`: en `"6'2 • 188 cm"` es `188 cm`. Las alturas vienen en `cm` o `meters` y los pesos en `kg` o `tons`; lleven metros a centímetros y toneladas a kilogramos. Las comas separan miles.
- [ ] Dejar `"-"` y las alturas de 0 cm como nulos.
- [ ] Conservar los seis puntajes como enteros; si los seis son 0, convertirlos en nulos. Conservar los ceros de las fichas parciales, las que tienen algunos puntajes en 0 y otros con valor: su interpretación se revisará al agrupar.

Usen expresiones de Polars, sin transformar filas con ciclos. La celda que sigue a la suya comprueba el resultado: deben quedar 323 alturas nulas (307 `"-"` y 16 de 0 cm), 364 pesos nulos y 65 nulos en cada puntaje. Groot debe medir 701 cm y pesar 3 700 kg.

In [9]:
patron_altura = r"•\s*([\d.,]+)\s*(cm|meters)"
altura_valor = (
    pl.col("height")
    .str.extract(patron_altura, 1)
    .str.replace_all(",", "")
    .cast(pl.Float64)
)
altura_unidad = pl.col("height").str.extract(patron_altura, 2)
altura_cm = pl.when(altura_unidad == "meters").then(altura_valor * 100).otherwise(
    altura_valor
)
altura_cm = (
    pl.when(altura_cm == 0)
    .then(None)
    .otherwise(altura_cm)
    .cast(pl.Float64)
    .alias("altura_cm")
)

patron_peso = r"•\s*([\d.,]+)\s*(kg|tons)"
peso_valor = (
    pl.col("weight")
    .str.extract(patron_peso, 1)
    .str.replace_all(",", "")
    .cast(pl.Float64)
)
peso_unidad = pl.col("weight").str.extract(patron_peso, 2)
peso_kg = (
    pl.when(peso_unidad == "tons")
    .then(peso_valor * 1000)
    .otherwise(peso_valor)
    .cast(pl.Float64)
    .alias("peso_kg")
)

sin_ficha = pl.all_horizontal(*(pl.col(c) == 0 for c in PUNTAJES))
puntajes_limpios = [
    pl.when(sin_ficha)
    .then(None)
    .otherwise(pl.col(c))
    .cast(pl.Int64)
    .alias(c)
    for c in PUNTAJES
]

medidas_exploradas = catalogo.select(
    "name", altura_cm, peso_kg, *puntajes_limpios
)

In [10]:
assert medidas_exploradas["name"].equals(catalogo["name"])
print(medidas_exploradas.null_count())
medidas_exploradas.filter(pl.col("name") == "Groot")

shape: (1, 9)
┌──────┬───────────┬─────────┬─────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ name ┆ altura_cm ┆ peso_kg ┆ intelligenc ┆ … ┆ speed_scor ┆ durability ┆ power_scor ┆ combat_sco │
│ ---  ┆ ---       ┆ ---     ┆ e_score     ┆   ┆ e          ┆ _score     ┆ e          ┆ re         │
│ u32  ┆ u32       ┆ u32     ┆ ---         ┆   ┆ ---        ┆ ---        ┆ ---        ┆ ---        │
│      ┆           ┆         ┆ u32         ┆   ┆ u32        ┆ u32        ┆ u32        ┆ u32        │
╞══════╪═══════════╪═════════╪═════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ 0    ┆ 323       ┆ 364     ┆ 65          ┆ … ┆ 65         ┆ 65         ┆ 65         ┆ 65         │
└──────┴───────────┴─────────┴─────────────┴───┴────────────┴────────────┴────────────┴────────────┘


name,altura_cm,peso_kg,intelligence_score,strength_score,speed_score,durability_score,power_score,combat_score
str,f64,f64,i64,i64,i64,i64,i64,i64
"""Groot""",701.0,3700.0,90,85,35,70,100,65


### 1.3 — Poderes como multi-hot (0,2 puntos)

<!-- DEFINICIÓN -->
<div style="padding:16px 20px; margin:16px 0; border-left:4px solid #3fb950; background:rgba(63,185,80,.12); color:inherit; border-radius:4px;">

  <strong style="display:block; margin-bottom:8px;">📖 Multi-hot y vocabulario aprendido</strong>

<strong>One-hot</strong> pone un 1 en la columna de la categoría de cada observación y 0 en las demás; <strong>multi-hot</strong> puede poner varios 1, uno por etiqueta. <code>MultiLabelBinarizer</code> aprende las etiquetas con <code>fit</code>, las guarda ordenadas en <code>classes_</code> y aplica esas mismas columnas con <code>transform</code>. <code>fit_transform</code> hace ambos pasos sobre los datos de ajuste. Ese conjunto de etiquetas aprendidas es el <strong>vocabulario</strong> del encoder. Una lista vacía deja todas las columnas en 0: expresa ausencia de etiquetas registradas.

Al llegar datos nuevos, el número y el significado de las columnas deben mantenerse. Por eso el encoder no se reajusta. Una etiqueta que no está en el vocabulario no tiene columna donde escribirse: <code>MultiLabelBinarizer</code> la descarta y emite una advertencia (<code>UserWarning</code>) que la nombra. La última línea de la celda siguiente lo muestra con una receta que trae merkén.
</div>

In [11]:
from sklearn.preprocessing import MultiLabelBinarizer

recetas = [["palta", "tomate"], ["queso"], []]
encoder_recetas = MultiLabelBinarizer().fit(recetas)
print("Columnas:", encoder_recetas.classes_)
print(encoder_recetas.transform([["tomate"], []]))
print(encoder_recetas.transform([["tomate", "merkén"]]))

Columnas: ['palta' 'queso' 'tomate']
[[0 0 1]
 [0 0 0]]
[[0 0 1]]


c:\Users\Asus\Laboratorio-de-Programaci-n-Cient-fica-para-Ciencia-de-DatosIA7202\labs\lab_8\.venv\Lib\site-packages\sklearn\preprocessing\_label.py:1016: UserWarning: unknown class(es) ['merkén'] will be ignored
  warnings.warn(


Construyan `poderes_explorados` a partir de `catalogo`, con `name`, `poderes` como lista de strings y `n_poderes` como la cantidad de poderes distintos. Eliminen etiquetas repetidas con `list.unique(maintain_order=True)` antes de contar: una etiqueta repetida no es otro poder. `superpowers` viene como `"['Flight', 'Super Strength']"`. El patrón `str.extract_all(r"'[^']+'")` toma cada texto entre comillas simples; después hay que quitarle las comillas con `list.eval(...)` (hint: `str.strip_chars`). No transformen filas con ciclos.

- [ ] Ajustar `binarizador` solo con las listas del catálogo y guardar su matriz en `poderes_multihot`.
- [ ] Definir `BINARIAS`, la lista de nombres de columna `poder_<etiqueta>`, en el orden de `binarizador.classes_` y conservando la escritura original de cada etiqueta.
- [ ] Construir `poderes_codificados_explorados`: conservar `name`, `poderes` y `n_poderes` y agregar el bloque multi-hot como `Int8` con `DataFrame.hstack` de Polars.
- [ ] Guardar `poderes_binarios`, la misma matriz como booleana, para comparar distancias después.

Cada fila debe seguir correspondiendo a la misma versión del personaje. La matriz debe tener 1 367 filas y 295 columnas; cada valor es 0 o 1. La lista vacía genera una fila de ceros. Los nombres de columnas vienen del encoder, no de una lista definida a mano.

In [12]:
poderes_explorados = catalogo.select(
    "name",
    (
        pl.col("superpowers")
        .str.extract_all(r"'[^']+'")
        .list.eval(pl.element().str.strip_chars("'"))
        .list.unique(maintain_order=True)
        .alias("poderes")
    ),
).with_columns(
    pl.col("poderes").list.len().cast(pl.Int64).alias("n_poderes")
)

binarizador = MultiLabelBinarizer()
poderes_multihot = binarizador.fit_transform(
    poderes_explorados["poderes"].to_list()
)
BINARIAS = [f"poder_{etiqueta}" for etiqueta in binarizador.classes_]

bloque_poderes = pl.DataFrame(
    poderes_multihot,
    schema=BINARIAS,
    orient="row",
).cast(pl.Int8)

poderes_codificados_explorados = poderes_explorados.hstack(bloque_poderes)

poderes_binarios = poderes_multihot.astype(bool)

In [13]:
print(f"Multi-hot: {poderes_multihot.shape}")
print(f"Fracción de unos: {poderes_multihot.mean():.3f}")
assert poderes_explorados["name"].equals(catalogo["name"])
assert poderes_multihot.shape == (1367, 295)
assert bloque_poderes.null_count().sum_horizontal().item() == 0
assert set(bloque_poderes.to_numpy().ravel()) <= {0, 1}

Multi-hot: (1367, 295)
Fracción de unos: 0.049


<!-- PREGUNTA -->
<div style="padding:16px 20px; margin:16px 0; border-left:4px solid #58a6ff; background:rgba(88,166,255,.12); color:inherit; border-radius:4px;">

  <strong style="display:block; margin-bottom:8px;">❓ Columnas binarias y poderes desconocidos</strong>

1. ¿Qué significa la media de una columna binaria generada por el encoder?
2. En el ejemplo de las recetas, el merkén desapareció sin error. ¿Por qué es importante que el equipo vea esa advertencia en vez de dejarla pasar?
3. Imaginen que este encoder funciona dentro de un sistema real que recibe personajes nuevos todos los días. ¿Qué pasaría con la representación y con los vecinos de un personaje cuyo único poder no está en el vocabulario? ¿Y si esos poderes nuevos se vuelven frecuentes?
4. ¿Qué estrategia usarían en este laboratorio ante un poder desconocido: descartarlo, reajustar el encoder, detener el proceso u otra? Justifiquen considerando que los personajes del catálogo deben conservar sus columnas.
</div>

**1.** La media de una binaria de poder es la proporción de personajes que lo tienen registrado.

**2.** La advertencia indica que el poder nuevo no quedó representado; ignorarla podría ocultar diferencias relevantes.

**3.** Si era su único poder, el personaje tendría todas las binarias en cero, quedando artificialmente parecido a otros sin poderes registrados.

**4.** Mantendría fijo el vocabulario para comparar ambos lotes. Si aparecen muchos poderes nuevos, actualizaría el encoder y volvería a codificar ambos lotes para mantener la consistencia.

### 1.4 — Selección de variables (0,1 puntos)

<!-- DEFINICIÓN -->
<div style="padding:16px 20px; margin:16px 0; border-left:4px solid #3fb950; background:rgba(63,185,80,.12); color:inherit; border-radius:4px;">

  <strong style="display:block; margin-bottom:8px;">📖 Variables nominales y ordinales</strong>
  Una variable <strong>ordinal</strong> tiene un orden con sentido (tallas S, M, L); una <strong>nominal</strong> no lo tiene (comunas, editoriales). <code>OrdinalEncoder</code> asigna un entero a cada categoría, en orden alfabético salvo que se indique otro. Para una variable nominal, esos enteros inventan distancias: codificar comunas deja a Macul (código 0) más cerca de Maipú (1) que de Ñuñoa (2), aunque Macul y Ñuñoa son vecinas.
</div>

In [14]:
from sklearn.preprocessing import OrdinalEncoder

comunas = pl.DataFrame({"comuna": ["Ñuñoa", "Macul", "Maipú"]})
OrdinalEncoder().fit(comunas).categories_

[array(['Macul', 'Maipú', 'Ñuñoa'], dtype=object)]

La celda siguiente codifica `creator` con `OrdinalEncoder`. Obsérvenla antes de responder.

In [15]:
codificador_ordinal = OrdinalEncoder().fit(
    catalogo.select(pl.col("creator").fill_null("desconocido"))
)
editoriales = list(codificador_ordinal.categories_[0])
print(f"{len(editoriales)} categorías")
for editorial in [
    "DC Comics",
    "Dark Horse Comics",
    "Marvel Comics",
    "Shueisha",
]:
    print(f"{editorial}: {editoriales.index(editorial)}")

40 categorías
DC Comics: 4
Dark Horse Comics: 5
Marvel Comics: 21
Shueisha: 29


<!-- PREGUNTA -->
<div style="padding:16px 20px; margin:16px 0; border-left:4px solid #58a6ff; background:rgba(88,166,255,.12); color:inherit; border-radius:4px;">

  <strong style="display:block; margin-bottom:8px;">❓ Preguntas</strong>
  <ol>
  <li>Con esta codificación, ¿qué editorial queda más cerca de Marvel Comics: DC Comics o Dark Horse Comics? ¿Por qué ese resultado no dice nada sobre los personajes?</li>
  <li>Independiente de cómo se codifique, ¿debería <code>creator</code> entrar en la representación que usaremos para buscar equivalentes de personajes de Marvel? Justifiquen con lo que pidió la Magneta.</li>
  <li>Si incluimos <code>gender</code> y <code>type_race</code>, ¿qué personajes quedarían más cerca solo por compartirlas? ¿Por qué esa información podría ayudar o perjudicar la búsqueda de personajes que jueguen parecido?</li>
  </ol>
</div>

**1.** Con el orden alfabético, DC Comics vale 4, Dark Horse Comics 5 y Marvel Comics 21. Por lo tanto, Dark Horse Comics queda más cerca de Marvel, pero esta distancia numérica no representa una similitud real entre editoriales.

**2.** `creator` sirve para filtrar editoriales, pero incluirlo en la distancia favorecería artificialmente personajes de la misma editorial.

**3.** `gender` y `type_race` pueden aportar similitud física, aunque también acercan personajes que juegan distinto. Su inclusión es una decisión de diseño.

Usaremos puntajes, medidas, `n_poderes`, `gender`, `type_race` y las binarias generadas desde `poderes`. `name` identifica filas; `creator` filtra equivalentes y `alignment` ayuda a describir grupos. `powers_text` se conserva para la etapa de texto. `anio_aparicion`, el año que se puede leer entre paréntesis en `first_appearance`, queda disponible para inspección, pero solo 394 de 1 367 filas tienen un año extraíble: imputar 973 valores haría que la mayor parte de esa columna fuese inventada.

### 1.5 — Trasladar las features al módulo (0,2 puntos)

Ya comprobamos las unidades, los puntajes y los poderes en el notebook. El siguiente paso es trasladar esas transformaciones a `src/heroverse/features.py`, de modo que exista una única implementación reutilizable tanto para el catálogo actual como para cualquier lote de personajes que llegue más adelante. `anio_aparicion` ya viene implementada en ese archivo como apoyo para una extensión opcional; no tienen que desarrollarla.

<!-- MODULARIZACIÓN -->
<div style="padding:16px 20px; margin:16px 0; border-left:4px solid #f0883e; background:rgba(240,136,62,.12); color:inherit; border-radius:4px;">

  <strong style="display:block; margin-bottom:8px;">🛠️ Modularización — Features</strong>

  Implementen en <code>src/heroverse/features.py</code> las funciones siguientes, que devuelven una expresión de Polars (<code>pl.Expr</code>), no un DataFrame:

  <ul>
    <li><code>altura_en_cm</code>: transforma <code>height</code> en una altura numérica expresada en centímetros y deja como <code>null</code> los valores que representan ausencia de información;</li>
    <li><code>peso_en_kg</code>: transforma <code>weight</code> en kilogramos, normalizando las distintas unidades presentes en el catálogo;</li>
    <li><code>lista_poderes</code>: transforma <code>superpowers</code> desde su representación textual a una lista de strings;</li>
    <li><code>puntajes_con_ficha</code>: conserva los seis puntajes cuando corresponden a una ficha con información y transforma sus valores centinela en faltantes.</li>
  </ul>

  Cada expresión debe respetar el contrato documentado en su docstring: nombre de la columna resultante, tipo de dato, unidad utilizada y criterio empleado para reconocer datos faltantes.

  <br>

  Luego implementen <code>construir_features(personajes)</code>

  Esta función debe recibir un <code>DataFrame</code> con el esquema de los CSV entregados y devolver una nueva tabla con <strong>una fila por observación y las variables necesarias para las siguientes etapas del laboratorio</strong>.

  La salida tiene, en este orden: <code>name</code>; las cuatro <code>CATEGORICAS</code> (<code>creator</code>, <code>gender</code>, <code>type_race</code> y <code>alignment</code>, sin cambios); los seis <code>PUNTAJES</code>; <code>altura_cm</code>, <code>peso_kg</code> y <code>anio_aparicion</code>; <code>poderes</code>, la lista sin etiquetas repetidas, y su largo <code>n_poderes</code>; y <code>powers_text</code> sin cambios, para la etapa 3. <code>CATEGORICAS</code> y <code>PUNTAJES</code> están en <code>columns.py</code>.

  Implementen también <code>ajustar_poderes(features)</code>, que devuelve una tupla <code>(binarizador, tabla)</code>: el binarizador ajustado y una copia de la tabla con las binarias <code>poder_*</code> agregadas. <code>transformar_poderes(features, binarizador)</code> aplica el vocabulario aprendido sin reajustar. Conserven filas y columnas; cada binaria es <code>Int8</code> y sigue el orden de <code>classes_</code>. Un poder desconocido se descarta con la advertencia de <code>MultiLabelBinarizer</code>, como discutieron en la 1.3.

  No codifiquen todavía las variables categóricas ni imputen sus faltantes: <code>gender</code>, <code>type_race</code> y las demás quedan como texto. Las codificaremos en la 1.7 con los transformadores de scikit-learn.

  <br>

  Antes de realizar cualquier transformación, <code>construir_features</code> debe comprobar que <code>name</code>:

  <ul>
    <li>no contiene valores <code>null</code>;</li>
    <li>no contiene valores repetidos.</li>
  </ul>

  Si alguna de estas condiciones no se cumple, la función debe levantar un <code>ValueError</code>. Esta precondición protege la <strong>unidad de observación</strong>: una fila de salida debe seguir correspondiendo exactamente a una fila identificable del catálogo.

  Finalmente, la función debe preservar el número y el orden de las observaciones. Construir features puede modificar columnas, pero no debe agregar, eliminar ni reordenar personajes.
</div>

In [16]:
from src.heroverse.columns import PUNTAJES
from src.heroverse.features import (
    ajustar_poderes,
    construir_features,
    transformar_poderes,
)

features = construir_features(catalogo)
binarizador_modulo, features_codificadas = ajustar_poderes(features)
assert list(binarizador_modulo.classes_) == list(binarizador.classes_)
binarizador = binarizador_modulo
features.select(
    pl.len().alias("filas"),
    pl.col(
        "altura_cm", "peso_kg", "strength_score", "anio_aparicion"
    ).null_count(),
)

filas,altura_cm,peso_kg,strength_score,anio_aparicion
u32,u32,u32,u32,u32
1367,323,364,65,973


<!-- COMPROBACIÓN -->
<div style="padding:16px 20px; margin:16px 0; border-left:4px solid #2da44e; background:rgba(45,164,78,.12); color:inherit; border-radius:4px;">

  <strong style="display:block; margin-bottom:8px;">🧪 Comprobación</strong>
  Ejecutar <code>uv run pytest -m etapa1 tests/test_features.py</code>. La celda de arriba debe mostrar 1 367 filas, 323 alturas nulas (307 <code>"-"</code> y 16 de 0 cm), 364 pesos nulos, 65 <code>strength_score</code> nulos y 973 <code>anio_aparicion</code> nulos.
</div>

In [17]:
assert features.select(medidas_exploradas.columns).equals(medidas_exploradas)
assert features_codificadas.select(
    poderes_codificados_explorados.columns
).equals(poderes_codificados_explorados)
print("El módulo reproduce las transformaciones exploradas.")

El módulo reproduce las transformaciones exploradas.


### 1.6 — Imputación y pipelines numéricos (0,4 puntos)

Inspeccionemos las distribuciones antes de transformar. Para calcular distancias no puede haber nulos, así que primero hay que **imputar**: rellenar cada faltante con un valor estimado a partir de los datos conocidos, en este caso la mediana de la columna. La mediana no introduce un valor extremo, pero concentra observaciones en un mismo valor: la imputación no recupera lo que desconocemos.

La celda siguiente guarda en `X_numerico` las nueve columnas numéricas imputadas y todavía sin escalar, y en `nombres` la lista de `name` en el orden de sus filas. Las dos se usan en la etapa 2.

In [18]:
import numpy as np
import plotly.express as px
from sklearn.impute import SimpleImputer

MEDIDAS = ["altura_cm", "peso_kg", "n_poderes"]
NUMERICAS = [*PUNTAJES, *MEDIDAS]
nombres = features["name"].to_list()
imputador_numerico = SimpleImputer(strategy="median")
X_numerico = imputador_numerico.fit_transform(features.select(NUMERICAS))
print(features.select(NUMERICAS).describe())
print("Medianas aprendidas:", imputador_numerico.statistics_)

shape: (9, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ intellige ┆ strength_ ┆ speed_sco ┆ … ┆ combat_sc ┆ altura_cm ┆ peso_kg   ┆ n_podere │
│ ---       ┆ nce_score ┆ score     ┆ re        ┆   ┆ ore       ┆ ---       ┆ ---       ┆ s        │
│ str       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ f64       ┆ f64       ┆ ---      │
│           ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆           ┆           ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 1302.0    ┆ 1302.0    ┆ 1302.0    ┆ … ┆ 1302.0    ┆ 1044.0    ┆ 1003.0    ┆ 1367.0   │
│ null_coun ┆ 65.0      ┆ 65.0      ┆ 65.0      ┆ … ┆ 65.0      ┆ 323.0     ┆ 364.0     ┆ 0.0      │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ 82.837942 ┆ 41.340246 ┆ 48.625192 ┆ … ┆ 71.474654 ┆ 237.71839 

Inspeccionen los seis puntajes en una figura con un histograma por panel. En una segunda figura, muestren en la primera fila las tres medidas en escala original y, en la segunda, `log1p` de la altura y del peso, para ver cómo cambia su forma. Cada panel debe indicar su variable y escala. Antes de elegir el escalamiento, identifiquen las colas largas: pocos valores muy grandes, lejos de la mayoría.

In [19]:
from plotly.subplots import make_subplots
import plotly.graph_objects as go

fig_puntajes = make_subplots(
    rows=2,
    cols=3,
    subplot_titles=PUNTAJES,
)
for i, columna in enumerate(PUNTAJES):
    fig_puntajes.add_trace(
        go.Histogram(
            x=features[columna].drop_nulls().to_list(),
            name=columna,
            showlegend=False,
        ),
        row=i // 3 + 1,
        col=i % 3 + 1,
    )
fig_puntajes.update_layout(
    title="Distribución de los seis puntajes",
    height=650,
)
fig_puntajes.show()

fig_medidas = make_subplots(
    rows=2,
    cols=3,
    subplot_titles=[
        "altura_cm — original",
        "peso_kg — original",
        "n_poderes — original",
        "altura_cm — log1p",
        "peso_kg — log1p",
        "",
    ],
)

for j, columna in enumerate(MEDIDAS):
    fig_medidas.add_trace(
        go.Histogram(
            x=features[columna].drop_nulls().to_list(),
            name=columna,
            showlegend=False,
        ),
        row=1,
        col=j + 1,
    )

fig_medidas.add_trace(
    go.Histogram(
        x=np.log1p(features["altura_cm"].drop_nulls().to_numpy()),
        showlegend=False,
    ),
    row=2,
    col=1,
)
fig_medidas.add_trace(
    go.Histogram(
        x=np.log1p(features["peso_kg"].drop_nulls().to_numpy()),
        showlegend=False,
    ),
    row=2,
    col=2,
)
fig_medidas.update_layout(title="Medidas: escala original vs. log1p", height=650)
fig_medidas.show()

<!-- DEFINICIÓN -->
<div style="padding:16px 20px; margin:16px 0; border-left:4px solid #3fb950; background:rgba(63,185,80,.12); color:inherit; border-radius:4px;">

  <strong style="display:block; margin-bottom:8px;">📖 Transformaciones de escala</strong>
  Sea $x$ una columna, con media $\bar{x}$, desviación estándar $s$, mínimo $x_{\min}$, máximo $x_{\max}$, mediana $\tilde{x}$ y rango intercuartílico $\mathrm{IQR}$ (percentil 75 menos percentil 25).
  <ul>
  <li><strong>Estandarización</strong> (<code>StandardScaler</code>): $z = (x - \bar{x}) / s$. Deja media 0 y desviación 1, pero $\bar{x}$ y $s$ se mueven mucho con un solo valor extremo.</li>
  <li><strong>Min-max</strong> (<code>MinMaxScaler</code>): $(x - x_{\min}) / (x_{\max} - x_{\min})$. Deja todo entre 0 y 1; si el máximo es extremo, el resto queda apretado cerca de 0.</li>
  <li><strong>Escalamiento robusto</strong> (<code>RobustScaler</code>): $(x - \tilde{x}) / \mathrm{IQR}$. Usa mediana e IQR, menos sensibles a valores extremos que media y desviación estándar.</li>
  <li><strong>Transformación logarítmica</strong>: $\log(1 + x)$. Comprime las colas largas: 10 y 10 000 pasan a 2,4 y 9,2. Se suma 1 para que un 0 no dé $-\infty$; en NumPy es <code>np.log1p</code>.</li>
  </ul>
  Ninguna es la correcta en general: la elección depende de la distribución de cada feature.
</div>

<!-- PREGUNTA -->
<div style="padding:16px 20px; margin:16px 0; border-left:4px solid #58a6ff; background:rgba(88,166,255,.12); color:inherit; border-radius:4px;">

  <strong style="display:block; margin-bottom:8px;">❓ Elección antes de transformar</strong>
  1. A partir de las distribuciones, ¿qué transformación proponen para los puntajes y cuál para las medidas?
2. ¿Por qué min-max puede comprimir casi todos los pesos cerca de 0? ¿Qué problema de los valores extremos no resuelve un escalamiento robusto?
</div>

**1.** Usaría mediana y `StandardScaler` para puntajes acotados de 0 a 100; para las medidas, mediana, `log1p` y `RobustScaler`, porque presentan colas largas.

**2.** Un peso cercano a 99 millones de kg haría que min-max concentrara casi todos los otros cerca de cero. `RobustScaler` resiste ese extremo, pero no lo comprime: eso lo hace `log1p`.

<!-- DEFINICIÓN -->
<div style="padding:16px 20px; margin:16px 0; border-left:4px solid #3fb950; background:rgba(63,185,80,.12); color:inherit; border-radius:4px;">

  <strong style="display:block; margin-bottom:8px;">📖 Pipeline: una secuencia de transformaciones</strong>
  Un <strong><code>Pipeline</code></strong> encadena operaciones: al ajustar, cada transformador aprende con la salida del anterior; al transformar datos nuevos, aplica los parámetros ya aprendidos en el mismo orden. <code>SimpleImputer</code> aprende una mediana, <code>StandardScaler</code> aprende media y desviación, y <code>RobustScaler</code> mediana e IQR. <code>log1p</code> no aprende parámetros; <code>FunctionTransformer</code> permite incorporarlo a la secuencia, y <code>feature_names_out="one-to-one"</code> le indica que cada columna conserva su nombre. <code>set_output(transform="polars")</code> hace que la salida sea un DataFrame de Polars con nombres, en vez de un arreglo de NumPy.
</div>

In [20]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import FunctionTransformer, StandardScaler

consumos = pl.DataFrame({"consumo_kwh": [80.0, None, 150.0, 900.0]})
pipeline_consumo = Pipeline(
    [
        ("imputar", SimpleImputer(strategy="median")),
        ("log", FunctionTransformer(np.log1p, feature_names_out="one-to-one")),
        ("escalar", StandardScaler()),
    ]
).set_output(transform="polars")
print(pipeline_consumo.fit_transform(consumos))
print(pipeline_consumo.transform(pl.DataFrame({"consumo_kwh": [120.0]})))

shape: (4, 1)
┌─────────────┐
│ consumo_kwh │
│ ---         │
│ f64         │
╞═════════════╡
│ -1.015176   │
│ -0.323158   │
│ -0.323158   │
│ 1.661492    │
└─────────────┘
shape: (1, 1)
┌─────────────┐
│ consumo_kwh │
│ ---         │
│ f64         │
╞═════════════╡
│ -0.569251   │
└─────────────┘


Construyan `pipeline_puntajes` con mediana y `StandardScaler`, y `pipeline_medidas` con mediana, `log1p` y `RobustScaler`. Ajusten ambos solo con el catálogo. Guarden sus salidas en `puntajes_transformados` y `medidas_transformadas`, como DataFrames de Polars con los nombres originales.

Construyan además `X_estandar` aplicando `StandardScaler` a `X_numerico`, y `X_log_robusto` pasando las dos salidas anteriores a arreglos (`to_numpy()`) y uniéndolas con `np.hstack`, en el orden de `NUMERICAS`. Cada matriz debe tener 1 367 filas y nueve columnas, sin faltantes. Las compararemos en la etapa 2.

En la 5.4 combinaremos los puntajes con el texto de los poderes. Para eso, construyan también `puntajes_unitarios_catalogo`.

- [ ] Dividan cada fila de `puntajes_transformados` por su norma euclidiana $\lVert x \rVert_2 = \sqrt{\sum_j x_j^2}$, donde $x_j$ es el puntaje $j$ de esa fila. Por ejemplo, $(3, 4)$ tiene norma 5 y pasa a $(0{,}6;\ 0{,}8)$.
- [ ] Si la norma de una fila es 0, la fila debe quedar en ceros: calculen las normas con `np.linalg.norm(..., axis=1, keepdims=True)` y usen `.clip(1e-9)` en el denominador para no dividir por 0.

Ojo con la diferencia: los escaladores anteriores transforman **columnas**; esta operación normaliza **filas**. Conserva la dirección del vector y descarta su largo, así que dos perfiles proporcionales quedan iguales. Como los puntajes ya están centrados y escalados, la dirección describe en qué se destaca un personaje respecto del resto del catálogo, no su nivel absoluto de capacidad.

In [21]:
from sklearn.preprocessing import RobustScaler

pipeline_puntajes = Pipeline(
    [
        ("imputar", SimpleImputer(strategy="median")),
        ("escalar", StandardScaler()),
    ]
).set_output(transform="polars")
puntajes_transformados = pipeline_puntajes.fit_transform(features.select(PUNTAJES))

pipeline_medidas = Pipeline(
    [
        ("imputar", SimpleImputer(strategy="median")),
        (
            "log",
            FunctionTransformer(np.log1p, feature_names_out="one-to-one"),
        ),
        ("escalar", RobustScaler()),
    ]
).set_output(transform="polars")
medidas_transformadas = pipeline_medidas.fit_transform(features.select(MEDIDAS))

X_estandar = StandardScaler().fit_transform(X_numerico)

X_log_robusto = np.hstack(
    [puntajes_transformados.to_numpy(), medidas_transformadas.to_numpy()]
)

puntajes_array = puntajes_transformados.to_numpy()
normas = np.linalg.norm(puntajes_array, axis=1, keepdims=True)
puntajes_unitarios_catalogo = puntajes_array / normas.clip(1e-9)

In [22]:
print(puntajes_transformados.describe())
print(medidas_transformadas.describe())
assert X_numerico.shape == X_estandar.shape == X_log_robusto.shape == (1367, 9)
assert np.isfinite(X_log_robusto).all()

shape: (9, 7)
┌────────────┬──────────────┬──────────────┬─────────────┬─────────────┬─────────────┬─────────────┐
│ statistic  ┆ intelligence ┆ strength_sco ┆ speed_score ┆ durability_ ┆ power_score ┆ combat_scor │
│ ---        ┆ _score       ┆ re           ┆ ---         ┆ score       ┆ ---         ┆ e           │
│ str        ┆ ---          ┆ ---          ┆ f64         ┆ ---         ┆ f64         ┆ ---         │
│            ┆ f64          ┆ f64          ┆             ┆ f64         ┆             ┆ f64         │
╞════════════╪══════════════╪══════════════╪═════════════╪═════════════╪═════════════╪═════════════╡
│ count      ┆ 1367.0       ┆ 1367.0       ┆ 1367.0      ┆ 1367.0      ┆ 1367.0      ┆ 1367.0      │
│ null_count ┆ 0.0          ┆ 0.0          ┆ 0.0         ┆ 0.0         ┆ 0.0         ┆ 0.0         │
│ mean       ┆ 4.9899e-16   ┆ -6.2374e-17  ┆ 4.1583e-17  ┆ 1.8712e-16  ┆ 3.5345e-16  ┆ 1.2475e-16  │
│ std        ┆ 1.000366     ┆ 1.000366     ┆ 1.000366    ┆ 1.000366    ┆ 1.00

### 1.7 — Pipeline categórico (0,3 puntos)

<!-- DEFINICIÓN -->
<div style="padding:16px 20px; margin:16px 0; border-left:4px solid #3fb950; background:rgba(63,185,80,.12); color:inherit; border-radius:4px;">

  <strong style="display:block; margin-bottom:8px;">📖 One-hot, infrecuentes y desconocidas</strong>
  <code>OneHotEncoder</code> crea una columna binaria por categoría, y así ninguna queda más cerca de otra. Con muchas categorías raras, eso agrega columnas que casi siempre valen 0. <code>min_frequency=m</code> junta las categorías con menos de $m$ apariciones en una sola columna, <code>infrequent_sklearn</code>. <code>handle_unknown="infrequent_if_exist"</code> manda a esa columna una categoría nueva si existe un grupo de infrecuentes; si no existe, todas las columnas de esa variable quedan en 0 para esa fila.
</div>

In [23]:
from sklearn.preprocessing import OneHotEncoder

comunas_ajuste = pl.DataFrame(
    {"comuna": ["Ñuñoa", "Ñuñoa", "Macul", "Macul", "Lo Barnechea"]}
)
codificador_comunas = OneHotEncoder(
    handle_unknown="infrequent_if_exist", min_frequency=2, sparse_output=False
).set_output(transform="polars")
codificador_comunas.fit(comunas_ajuste)
codificador_comunas.transform(
    pl.DataFrame({"comuna": ["Macul", "Lo Barnechea", "Vitacura"]})
)

comuna_Macul,comuna_Ñuñoa,comuna_infrequent_sklearn
f64,f64,f64
1.0,0.0,0.0
0.0,0.0,1.0
0.0,0.0,1.0


Muestren cuántas razas distintas tiene `type_race`, sin contar los nulos, cuántas razas tienen menos de 10 personajes y cuántos valores nulos hay. El umbral de 10 es el `min_frequency` que usaremos en el encoder.

In [24]:
frecuencias_razas = (
    catalogo
    .filter(pl.col("type_race").is_not_null())
    .group_by("type_race")
    .len()
)

n_razas = catalogo["type_race"].drop_nulls().n_unique()
n_razas_menor_10 = frecuencias_razas.filter(pl.col("len") < 10).height
nulos_raza = catalogo["type_race"].null_count()

print(f"Razas distintas (sin nulos): {n_razas}")
print(f"Razas con menos de 10 personajes: {n_razas_menor_10}")
print(f"Valores nulos de type_race: {nulos_raza}")

Razas distintas (sin nulos): 67
Razas con menos de 10 personajes: 49
Valores nulos de type_race: 360


<!-- PREGUNTA -->
<div style="padding:16px 20px; margin:16px 0; border-left:4px solid #58a6ff; background:rgba(88,166,255,.12); color:inherit; border-radius:4px;">

  <strong style="display:block; margin-bottom:8px;">❓ Predicción antes de codificar</strong>
  Antes de codificar, los nulos se reemplazarán por la categoría <code>desconocido</code>, que tendrá su propia columna.
  <ol>
  <li>Con lo que acaban de contar, ¿cuántas columnas esperan que produzca <code>type_race</code> con <code>min_frequency=10</code>, contando la de <code>desconocido</code> y la de infrecuentes?</li>
  <li>¿Qué columna tendrá encendida un personaje nuevo cuya raza no aparece en el catálogo?</li>
  </ol>
</div>

**1.** Hay 67 razas: 18 frecuentes, 49 poco frecuentes, `desconocido` y un grupo de infrecuentes. Espero 20 columnas para raza.

**2.** Una raza nueva entra en `infrequent_sklearn`, sin cambiar las columnas.

<!-- TIP -->
<div style="padding:16px 20px; margin:16px 0; border-left:4px solid #2f81f7; background:rgba(47,129,247,.12); color:inherit; border-radius:4px;">

  <strong style="display:block; margin-bottom:8px;">💡 Nulos de texto</strong>
  Un nulo de una columna de texto de Polars llega a scikit-learn como <code>None</code>, no como <code>NaN</code>. Para que <code>SimpleImputer</code> lo reconozca hay que indicarle <code>missing_values=None</code>.
</div>

Construyan `pipeline_categorico` para `gender` y `type_race` con dos pasos:

- [ ] un `SimpleImputer(missing_values=None, strategy="constant", fill_value="desconocido")`, que reemplaza los nulos por `"desconocido"`;
- [ ] un `OneHotEncoder` con `min_frequency=10`, `handle_unknown="infrequent_if_exist"` y `sparse_output=False`. Este último es necesario porque la salida será un DataFrame de Polars, que no admite matrices dispersas.

Usen `set_output(transform="polars")`, ajústenlo con `features.select(["gender", "type_race"])` y guarden su salida en `categoricas_codificadas`.

In [25]:
pipeline_categorico = Pipeline(
    [
        (
            "imputar",
            SimpleImputer(
                missing_values=None,
                strategy="constant",
                fill_value="desconocido",
            ),
        ),
        (
            "onehot",
            OneHotEncoder(
                min_frequency=10,
                handle_unknown="infrequent_if_exist",
                sparse_output=False,
            ),
        ),
    ]
).set_output(transform="polars")

categoricas_codificadas = pipeline_categorico.fit_transform(
    features.select(["gender", "type_race"])
)

In [26]:
print(f"{categoricas_codificadas.width} columnas")
categoricas_codificadas.columns

23 columnas


['gender_Female',
 'gender_Male',
 'gender_desconocido',
 'type_race_Alien',
 'type_race_Android',
 'type_race_Animal',
 'type_race_Asgardian',
 'type_race_Atlantean',
 'type_race_Cosmic Entity',
 'type_race_Cyborg',
 'type_race_Demi-God',
 'type_race_Demon',
 'type_race_God / Eternal',
 'type_race_Human',
 'type_race_Human / Altered',
 'type_race_Human / Radiation',
 'type_race_Inhuman',
 'type_race_Kryptonian',
 'type_race_Metahuman',
 'type_race_Mutant',
 'type_race_New God',
 'type_race_desconocido',
 'type_race_infrequent_sklearn']

<!-- PREGUNTA -->
<div style="padding:16px 20px; margin:16px 0; border-left:4px solid #58a6ff; background:rgba(88,166,255,.12); color:inherit; border-radius:4px;">

  <strong style="display:block; margin-bottom:8px;">❓ Preguntas</strong>
  <ol>
  <li>¿Se cumplió su predicción sobre el número de columnas? ¿Qué se pierde al juntar las razas raras?</li>
  <li>Los nulos quedaron como la categoría <code>desconocido</code> en vez de imputarse con la raza más frecuente. ¿Qué error evita esa decisión? Consideren que 360 personajes no tienen raza.</li>
  <li>¿Por qué el codificador se ajusta con el catálogo y no con el catálogo más los personajes nuevos? Piensen en qué pasaría con la columna de un personaje del catálogo si llegara un lote con otras razas.</li>
  </ol>
</div>

**1.** Sí: 20 columnas de raza y 3 de género, 23 en total. Agrupar categorías raras pierde su identidad particular.

**2.** Rellenar 360 razas desconocidas como `Human` inventaría información; `desconocido` evita eso.

**3.** Ajustar solo con el catálogo mantiene constantes las columnas y sus escalas al transformar personajes nuevos.

### 1.8 — Integración, datos nuevos y preprocesador (0,3 puntos)

<!-- DEFINICIÓN -->
<div style="padding:16px 20px; margin:16px 0; border-left:4px solid #3fb950; background:rgba(63,185,80,.12); color:inherit; border-radius:4px;">

  <strong style="display:block; margin-bottom:8px;">📖 ColumnTransformer: distintas operaciones por familia</strong>
  <code>Pipeline</code> encadena pasos sobre una entrada; <strong><code>ColumnTransformer</code></strong> reparte las columnas entre transformadores y concatena sus salidas. Cada bloque se declara con un nombre, un transformador y una lista de columnas. <code>"passthrough"</code> conserva un bloque sin transformarlo. Las columnas no seleccionadas se descartan por defecto; <code>verbose_feature_names_out=False</code> evita prefijos de bloque y <code>set_output(transform="polars")</code> conserva una salida con nombres.
</div>

In [27]:
from sklearn.compose import ColumnTransformer

viviendas = pl.DataFrame(
    {
        "superficie_m2": [40.0, 80.0, 120.0],
        "tipo": ["casa", "depto", "casa"],
    }
)
transformador_viviendas = ColumnTransformer(
    [
        ("superficie", StandardScaler(), ["superficie_m2"]),
        ("tipo", OneHotEncoder(sparse_output=False), ["tipo"]),
    ],
    verbose_feature_names_out=False,
).set_output(transform="polars")
transformador_viviendas.fit_transform(viviendas)

superficie_m2,tipo_casa,tipo_depto
f64,f64,f64
-1.224745,1.0,0.0
0.0,0.0,1.0
1.224745,1.0,0.0


Construyan `columnas_exploradas`, un `ColumnTransformer` que combine `pipeline_puntajes`, `pipeline_medidas`, `pipeline_categorico` y las `BINARIAS` de `features_codificadas` sin cambios. Usen solo `gender` y `type_race` como categóricas y salida Polars sin prefijos de bloque. Guarden el resultado ajustado a `features_codificadas` en `tabular_explorado`. `features_codificadas` salió de un `hstack` dentro de `ajustar_poderes`, que une tablas por posición y no por clave: comprueben que su columna `name` coincide con la de `features`.

La tabla debe conservar 1 367 filas y tener 327 columnas: seis puntajes, tres medidas, 23 columnas categóricas y 295 binarias. Ojo: hay 295 columnas de poderes y solo seis puntajes. Aunque cada binaria valga 0 o 1, el bloque de poderes puede pesar más en la distancia euclidiana solo por tener más columnas. No deben entrar identificadores, editorial, alineamiento, año ni texto.

In [28]:
assert features_codificadas["name"].equals(features["name"])

columnas_exploradas = ColumnTransformer(
    [
        ("puntajes", pipeline_puntajes, PUNTAJES),
        ("medidas", pipeline_medidas, MEDIDAS),
        ("categoricas", pipeline_categorico, ["gender", "type_race"]),
        ("binarias", "passthrough", BINARIAS),
    ],
    verbose_feature_names_out=False,
).set_output(transform="polars")

tabular_explorado = columnas_exploradas.fit_transform(features_codificadas)

print("Forma de la representación tabular:", tabular_explorado.shape)
assert tabular_explorado.shape == (1367, 327)
assert tabular_explorado.null_count().sum_horizontal().item() == 0

Forma de la representación tabular: (1367, 327)


Construyan `nuevos_features` con `construir_features(nuevos)` y `nuevos_features_codificadas` con `transformar_poderes(nuevos_features, binarizador)`. Luego construyan `nuevos_tabular_explorado` con `columnas_exploradas.transform(nuevos_features_codificadas)`. No reajusten con el lote nuevo. Una categoría nominal nueva cae en el grupo de infrecuentes; un poder nuevo, en cambio, no tiene columna que lo represente y se descarta con la advertencia que discutieron en la 1.3. Comprueben que las columnas coinciden con las del catálogo y que transformar una fila sola produce el mismo resultado que esa fila dentro del lote: así verifican que la transformación no aprende nada del lote, y que cada personaje se representa igual llegue solo o acompañado.

In [29]:
nuevos_features = construir_features(nuevos)
nuevos_features_codificadas = transformar_poderes(nuevos_features, binarizador)
nuevos_tabular_explorado = columnas_exploradas.transform(
    nuevos_features_codificadas
)

assert nuevos_tabular_explorado.columns == tabular_explorado.columns

primera_sola = columnas_exploradas.transform(nuevos_features_codificadas.head(1))
assert np.allclose(
    primera_sola.to_numpy(),
    nuevos_tabular_explorado.head(1).to_numpy(),
)

print("Catálogo:", tabular_explorado.shape)
print("Nuevos:", nuevos_tabular_explorado.shape)
print("Mismas columnas:", nuevos_tabular_explorado.columns == tabular_explorado.columns)

Catálogo: (1367, 327)
Nuevos: (81, 327)
Mismas columnas: True


<!-- MODULARIZACIÓN -->
<div style="padding:16px 20px; margin:16px 0; border-left:4px solid #f0883e; background:rgba(240,136,62,.12); color:inherit; border-radius:4px;">

  <strong style="display:block; margin-bottom:8px;">🛠️ Modularización — Preprocesador</strong>
  Implementen <code>construir_preprocesador(puntajes, medidas, categoricas, binarias, min_frequency)</code> en <code>src/heroverse/preprocessing.py</code>. Devuelve un <code>Pipeline</code> sin ajustar cuyo único paso, <code>"columnas"</code>, es un <code>ColumnTransformer</code> con las decisiones de esta etapa: puntajes imputados con la mediana y estandarizados; medidas imputadas con la mediana, con <code>log1p</code> y escalamiento robusto; categóricas con <code>desconocido</code> y one-hot con infrecuentes; y binarias sin cambios. La salida es un DataFrame de Polars.
</div>

In [30]:
from src.heroverse.preprocessing import construir_preprocesador

preprocesador = construir_preprocesador(
    PUNTAJES, MEDIDAS, ["gender", "type_race"], BINARIAS, min_frequency=10
)
tabular = preprocesador.fit_transform(features_codificadas)
nuevos_features = construir_features(nuevos)
nuevos_features_codificadas = transformar_poderes(nuevos_features, binarizador)
nuevos_tabular = preprocesador.transform(nuevos_features_codificadas)
assert tabular.columns == tabular_explorado.columns
assert np.allclose(tabular.to_numpy(), tabular_explorado.to_numpy())
assert np.allclose(
    nuevos_tabular.to_numpy(), nuevos_tabular_explorado.to_numpy()
)
print(f"Catálogo: {tabular.shape}; nuevos: {nuevos_tabular.shape}")
print(f"Mismas columnas: {tabular.columns == nuevos_tabular.columns}")

Catálogo: (1367, 327); nuevos: (81, 327)
Mismas columnas: True


<!-- COMPROBACIÓN -->
<div style="padding:16px 20px; margin:16px 0; border-left:4px solid #2da44e; background:rgba(45,164,78,.12); color:inherit; border-radius:4px;">

  <strong style="display:block; margin-bottom:8px;">🧪 Comprobación</strong>
  Ejecutar <code>uv run pytest -m etapa1</code>. La celda de arriba debe mostrar <code>(1367, 327)</code> para el catálogo, <code>(81, 327)</code> para los nuevos y <code>Mismas columnas: True</code>.
</div>

---
## Etapa 2 — Distancias y vecinos (0,8 puntos)

<!-- LORE -->
<div style="padding:16px 20px; margin:16px 0; border-left:4px solid #0f9e99; background:rgba(15,158,153,.12); color:inherit; border-radius:4px;">

  <strong style="display:block; margin-bottom:8px;">📜 Groot y los robots</strong>
  Con las features ya numéricas, la Magneta probó su primera búsqueda: «personajes parecidos a Groot». Le salieron Bumblebee, Iron Monger y Soundwave. «Son todos robots de varias toneladas», escribió, «Groot es un árbol». Tiene razón en sospechar: los números están bien, pero no todos pesan lo mismo en la comparación.
</div>

<!-- DEFINICIÓN -->
<div style="padding:16px 20px; margin:16px 0; border-left:4px solid #3fb950; background:rgba(63,185,80,.12); color:inherit; border-radius:4px;">

  <strong style="display:block; margin-bottom:8px;">📖 Distancia euclidiana y vecinos más cercanos</strong>
  Si cada personaje es un vector $x = (x_1, \dots, x_p)$ con $p$ features, la <strong>distancia euclidiana</strong> entre $x$ e $y$ es

  $$d(x, y) = \sqrt{\sum_{j=1}^{p} (x_j - y_j)^2}.$$

  Los <strong>vecinos más cercanos</strong> (<em>nearest neighbors</em>) de un personaje son los que tienen menor distancia a él. Como cada término es una diferencia al cuadrado, una feature cuyo rango es de miles domina la suma frente a otra cuyo rango es de decenas. Pensemos en departamentos descritos por precio en pesos y número de dormitorios: una diferencia de un dormitorio aporta 1 a la suma, y una de un millón de pesos aporta $10^{12}$.
</div>

In [31]:
import numpy as np
from sklearn.neighbors import NearestNeighbors

departamentos = np.array(
    [
        [95_000_000, 2],  # consulta
        [96_000_000, 5],  # precio casi igual, tres dormitorios más
        [110_000_000, 2],  # mismos dormitorios, más caro
    ]
)
_, indices = (
    NearestNeighbors(n_neighbors=2)
    .fit(departamentos)
    .kneighbors(departamentos[:1])
)
print("Vecino del primer departamento:", indices[0][1])

Vecino del primer departamento: 1


El vecino es el departamento 1, con tres dormitorios más: la diferencia de dormitorios ni se nota al lado del millón de pesos.

Para la búsqueda utilizaremos las tres matrices numéricas de la 1.6: `X_numerico`, sin escalar; `X_estandar`, estandarizada, y `X_log_robusto`, con logaritmo y escalamiento robusto en las medidas. Comparemos qué vecinos produce cada una.

### 2.1 — Predicción (0,1 puntos)

<!-- PREGUNTA -->
<div style="padding:16px 20px; margin:16px 0; border-left:4px solid #58a6ff; background:rgba(88,166,255,.12); color:inherit; border-radius:4px;">

  <strong style="display:block; margin-bottom:8px;">❓ Predicción</strong>
  Groot pesa 3 700 kg y sus puntajes están entre 35 y 100. Antes de calcular nada, piensen en <code>X_numerico</code>, sin escalar:
  <ol>
  <li>¿Qué feature decidirá sus vecinos?</li>
  <li>¿Qué tendrán en común esos vecinos?</li>
  </ol>
</div>

**1.** Dominará el peso, porque sus diferencias en kg superan ampliamente las de los puntajes, al estar estos acotados.

**2.** Espero personajes de peso parecido, aunque sus poderes u otras características no lo sean.

### 2.2 — Vecinos sin escalar (0,2 puntos)

Completen `vecinos_de`: debe devolver un DataFrame con `name` y `distancia` de los `k` vecinos más cercanos de `consulta` en la matriz `X`, ordenados por distancia y sin incluir a la consulta. Las filas de `X` siguen el orden de `nombres`, la lista que construimos en la 1.6 (hint: `NearestNeighbors` y su método `kneighbors`; pidan `k + 1` vecinos, porque el más cercano es la propia consulta).

In [32]:
def vecinos_de(X, consulta: str, k: int = 5) -> pl.DataFrame:
    """Busca vecinos euclidianos en la matriz X sin incluir la consulta."""
    if consulta not in nombres:
        raise KeyError(f"{consulta!r} no está en nombres")

    indice_consulta = nombres.index(consulta)
    modelo = NearestNeighbors(
        n_neighbors=min(k + 1, len(nombres)),
        metric="euclidean",
    ).fit(X)

    distancias, indices = modelo.kneighbors(
        X[indice_consulta : indice_consulta + 1]
    )
    indices = indices[0]
    distancias = distancias[0]

    mascara = indices != indice_consulta
    indices = indices[mascara][:k]
    distancias = distancias[mascara][:k]

    nombres_array = np.asarray(nombres, dtype=object)
    return pl.DataFrame(
        {
            "name": nombres_array[indices].tolist(),
            "distancia": distancias.astype(float).tolist(),
        }
    )

Los cinco vecinos de Groot sobre `X_numerico`, junto con los datos que permiten juzgarlos:

In [33]:
vecinos_crudos = vecinos_de(X_numerico, "Groot")
vecinos_crudos.join(features, on="name", maintain_order="left").select(
    "name", "distancia", "strength_score", "altura_cm", "peso_kg"
)

name,distancia,strength_score,altura_cm,peso_kg
str,f64,i64,f64,f64
"""Bumblebee""",733.938008,55,488.0,3000.0
"""Soundwave""",1323.869329,80,945.0,5000.0
"""Iron Monger""",1874.714645,65,null,1900.0
"""Lagoon Boy""",1953.497632,50,249.0,1800.0
"""Samurai Mech(Stone Army)""",2725.195956,45,399.0,992.0


### 2.3 — Efecto de las escalas (0,1 puntos)

Con `vecinos_de`, muestren los cinco vecinos de Groot sobre `X_estandar` y sobre `X_log_robusto`, junto con su fuerza, altura y peso (hint: el `join` de la celda anterior). Las matrices ya están construidas: aquí evaluamos su efecto sobre la similitud.

In [34]:
for etiqueta, matriz in [("Estándar", X_estandar), ("Log + robusto", X_log_robusto)]:
    print(etiqueta)
    display(
        vecinos_de(matriz, "Groot")
        .join(features, on="name", maintain_order="left")
        .select("name", "distancia", "strength_score", "altura_cm", "peso_kg")
    )

Estándar


name,distancia,strength_score,altura_cm,peso_kg
str,f64,i64,f64,f64
"""Toxin""",1.241387,80,191.0,117.0
"""Mantis""",1.315123,100,193.0,null
"""Sinestro""",1.338975,85,201.0,92.0
"""Maxima""",1.366253,90,180.0,72.0
"""Bloodaxe""",1.428608,80,218.0,495.0


Log + robusto


name,distancia,strength_score,altura_cm,peso_kg
str,f64,i64,f64,f64
"""Soundwave""",5.081622,80,945.0,5000.0
"""Bumblebee""",5.854917,55,488.0,3000.0
"""Fin Fang Foom""",8.168936,80,975.0,18000.0
"""Samurai Mech(Stone Army)""",10.054198,45,399.0,992.0
"""The Great Devourer""",13.163998,100,998.0,198.0


<!-- PREGUNTA -->
<div style="padding:16px 20px; margin:16px 0; border-left:4px solid #58a6ff; background:rgba(88,166,255,.12); color:inherit; border-radius:4px;">

  <strong style="display:block; margin-bottom:8px;">❓ Preguntas</strong>
  <ol>
  <li>Con <code>X_estandar</code>, los vecinos de Groot pesan entre 72 y 495 kg: el peso dejó de importar. Expliquen por qué usando la desviación estándar de <code>peso_kg</code> y los dos personajes más pesados del catálogo.</li>
  <li>Contrasten los vecinos observados con su elección de la 1.6: ¿qué evidencia muestra que logaritmo y escalamiento robusto recuperan la influencia del peso?</li>
  </ol>
</div>

**1.** La desviación del peso ronda 4,25 millones de kg, arrastrada por The Overlord (99 millones) y Shin Godzilla (91 millones). Así, una diferencia de miles de kg casi desaparece tras estandarizar.

**2.** Con `log1p` y escala robusta vuelven vecinos pesados, como Soundwave, Bumblebee y Fin Fang Foom. El peso recupera influencia sin imponer toda la distancia.

### 2.4 — Trasladar la búsqueda al módulo (0,2 puntos)

<!-- MODULARIZACIÓN -->
<div style="padding:16px 20px; margin:16px 0; border-left:4px solid #f0883e; background:rgba(240,136,62,.12); color:inherit; border-radius:4px;">

  <strong style="display:block; margin-bottom:8px;">🛠️ Modularización — Vecinos</strong>
  Trasladen <code>vecinos_de</code> a <code>vecinos_mas_cercanos(X, nombres, consulta, k, metrica)</code> en <code>src/heroverse/neighbors.py</code>. A diferencia de la versión del notebook, recibe <code>nombres</code> como argumento, acepta cualquier métrica de <code>NearestNeighbors</code> —la usaremos con Jaccard y coseno— y levanta <code>KeyError</code> si la consulta no existe. Sus valores por omisión son <code>k=5</code> y <code>metrica="euclidean"</code>; el contrato completo está en el docstring.
</div>

In [35]:
from src.heroverse.neighbors import vecinos_mas_cercanos

vecinos_mas_cercanos(X_log_robusto, nombres, "Groot")

name,distancia
str,f64
"""Soundwave""",5.081622
"""Bumblebee""",5.854917
"""Fin Fang Foom""",8.168936
"""Samurai Mech(Stone Army)""",10.054198
"""The Great Devourer""",13.163998


<!-- COMPROBACIÓN -->
<div style="padding:16px 20px; margin:16px 0; border-left:4px solid #2da44e; background:rgba(45,164,78,.12); color:inherit; border-radius:4px;">

  <strong style="display:block; margin-bottom:8px;">🧪 Comprobación</strong>
  Ejecutar <code>uv run pytest -m etapa2</code>. La celda de arriba debe mostrar los mismos cinco vecinos que <code>vecinos_de(X_log_robusto, "Groot")</code>, en el mismo orden.
</div>

### 2.5 — Poderes: euclidiana o Jaccard (0,2 puntos)

<!-- DEFINICIÓN -->
<div style="padding:16px 20px; margin:16px 0; border-left:4px solid #3fb950; background:rgba(63,185,80,.12); color:inherit; border-radius:4px;">

  <strong style="display:block; margin-bottom:8px;">📖 Distancia de Jaccard</strong>
  Para dos conjuntos $A$ y $B$, la <strong>distancia de Jaccard</strong> es

  $$d_J(A, B) = 1 - \frac{|A \cap B|}{|A \cup B|}.$$

  Con vectores binarios, la distancia euclidiana al cuadrado cuenta las posiciones en que difieren. Ninguna de las dos distancias cambia si agregamos columnas donde ambos valen 0; la diferencia es que Jaccard divide por la cantidad de elementos presentes en alguno de los dos. Por ejemplo, $A = \{\text{vuelo}\}$ y $B = \{\text{vuelo}, \text{fuerza}\}$ difieren en un poder: euclidiana al cuadrado 1 y Jaccard $1 - 1/2 = 0{,}5$. Dos personajes que comparten 19 poderes y difieren en uno también tienen euclidiana al cuadrado 1, pero Jaccard $1 - 19/20 = 0{,}05$. La euclidiana cuenta diferencias; Jaccard las pone en proporción. Un churrasco italiano (pan, carne, palta, tomate, mayo) y un barros luco (pan, carne, queso) comparten 2 de 6 ingredientes: $d_J = 1 - 2/6 \approx 0{,}67$.
</div>

Para dos conjuntos vacíos, la fórmula tiene denominador 0. scikit-learn sigue la convención de SciPy: distancia Jaccard 0 entre dos vectores vacíos. Es una decisión computacional, no evidencia de que sus capacidades reales sean iguales.

Usen `poderes_binarios`, construido en la 1.3. Con `vecinos_mas_cercanos`, muestren los cinco vecinos de Deadpool con la métrica euclidiana y con `metrica="jaccard"`, y cuenten cuántos personajes tienen las 295 columnas en 0.

In [36]:
for metrica in ["euclidean", "jaccard"]:
    print(metrica)
    display(vecinos_mas_cercanos(
        poderes_binarios.astype(bool), nombres, "Deadpool", metrica=metrica
    ))
print("Sin poderes registrados:", int((poderes_binarios.sum(axis=1) == 0).sum()))

euclidean


name,distancia
str,f64
"""Lady Deadpool""",2.236068
"""Evil Deadpool""",2.44949
"""Alita""",3.464102
"""The Executioner (MCU)""",3.464102
"""Knockout""",3.464102


jaccard


name,distancia
str,f64
"""Lady Deadpool""",0.227273
"""Evil Deadpool""",0.3
"""Angel Of Death""",0.52
"""Balder""",0.521739
"""Steppenwolf""",0.545455


Sin poderes registrados: 61


<!-- PREGUNTA -->
<div style="padding:16px 20px; margin:16px 0; border-left:4px solid #58a6ff; background:rgba(88,166,255,.12); color:inherit; border-radius:4px;">

  <strong style="display:block; margin-bottom:8px;">❓ Preguntas</strong>
  <ol>
  <li>¿Qué distancia euclidiana hay entre dos personajes sin poderes registrados? ¿Qué significa eso para sus vecinos más cercanos? ¿Y qué distancia Jaccard hay entre ellos?</li>
  <li>¿Qué criterio de parecido mide cada distancia? ¿Cuál recomendarían para comparar poderes en este encargo y por qué?</li>
  </ol>
</div>

**1.** Dos vectores de poderes vacíos tienen distancia euclidiana 0 y, por convención, también Jaccard 0. No implica que sus habilidades reales sean idénticas.

**2.** Euclidiana cuenta diferencias absolutas entre poderes; Jaccard las mide en proporción a su unión. Preferiría Jaccard, con cautela ante listas vacías.

---
## Etapa 3 — Texto: de palabras a vectores (1,2 puntos)

<!-- LORE -->
<div style="padding:16px 20px; margin:16px 0; border-left:4px solid #0f9e99; background:rgba(15,158,153,.12); color:inherit; border-radius:4px;">

  <strong style="display:block; margin-bottom:8px;">📜 «Lean lo que hacen»</strong>
  La Magneta revisó la tabla de 327 columnas y pidió complementar las etiquetas de poderes con sus descripciones: dos personajes con puntajes parecidos pueden jugar de maneras opuestas, uno a distancia con magia y otro cuerpo a cuerpo. «Superherodb trae una descripción de los poderes de cada uno», dice. «Úsenla». Hay que convertir ese texto en vectores comparables.
</div>

<!-- DEFINICIÓN -->
<div style="padding:16px 20px; margin:16px 0; border-left:4px solid #3fb950; background:rgba(63,185,80,.12); color:inherit; border-radius:4px;">

  <strong style="display:block; margin-bottom:8px;">📖 Tokens y bag of words</strong>
  <strong>Tokenizar</strong> es partir un texto en unidades, los <strong>tokens</strong>: palabras, trozos de palabras o signos. El <strong>bag of words</strong> representa cada texto con un vector que cuenta cuántas veces aparece cada palabra del vocabulario, sin importar el orden. <code>CountVectorizer</code> lo construye; las <strong>stop words</strong> son palabras muy frecuentes, como «el» o «de», que ayudan poco a distinguir un texto de otro y conviene descartar. scikit-learn solo trae la lista del inglés (<code>stop_words="english"</code>), así que en el ejemplo la pasamos a mano. Como casi todas las celdas del resultado valen 0, <code>CountVectorizer</code> lo devuelve como <strong>sparse matrix</strong> (matriz dispersa), que solo guarda las celdas distintas de 0; <code>.toarray()</code> la convierte en un arreglo común para mirarla.
</div>

In [37]:
from sklearn.feature_extraction.text import CountVectorizer

resenas = [
    "el completo italiano estaba rico",
    "el completo estaba frío",
    "la micro venía llena",
]
contador = CountVectorizer(stop_words=["el", "la", "estaba", "venía"])
conteos = contador.fit_transform(resenas)
pl.DataFrame(conteos.toarray(), schema=list(contador.get_feature_names_out()))

completo,frío,italiano,llena,micro,rico
i64,i64,i64,i64,i64,i64
1,0,1,0,0,1
1,1,0,0,0,0
0,0,0,1,1,0


<!-- DEFINICIÓN -->
<div style="padding:16px 20px; margin:16px 0; border-left:4px solid #3fb950; background:rgba(63,185,80,.12); color:inherit; border-radius:4px;">

  <strong style="display:block; margin-bottom:8px;">📖 TF-IDF</strong>
  <strong>TF-IDF</strong> pondera cada conteo por lo informativa que es la palabra. Para la palabra $t$ en el texto $d$, con $N$ textos en total y $\mathrm{df}(t)$ textos que contienen $t$,

  $$\mathrm{tfidf}(t, d) = \mathrm{tf}(t, d) \cdot \left(\ln \frac{1 + N}{1 + \mathrm{df}(t)} + 1\right),$$

  donde $\mathrm{tf}(t, d)$ es el conteo. Una palabra que está en todos los textos recibe el factor mínimo, 1: conserva su conteo, pero no gana peso. <code>TfidfVectorizer</code> normaliza cada fila que conserva al menos un token para que su norma euclidiana sea 1; las que pierden todos sus tokens quedan en ceros. Igual que los conteos, el resultado es una sparse matrix.
</div>

<!-- DEFINICIÓN -->
<div style="padding:16px 20px; margin:16px 0; border-left:4px solid #3fb950; background:rgba(63,185,80,.12); color:inherit; border-radius:4px;">

  <strong style="display:block; margin-bottom:8px;">📖 Similitud coseno</strong>
  La <strong>similitud coseno</strong> entre $a$ y $b$ es $\cos(a, b) = \frac{a \cdot b}{\lVert a \rVert\,\lVert b \rVert}$, y la distancia coseno es $1 - \cos(a, b)$. Mide el ángulo entre dos vectores, no su largo: una descripción larga y otra corta que usan las palabras en las mismas proporciones quedan a distancia 0. Si los vectores tienen norma 1, como las filas no vacías de TF-IDF, la similitud es simplemente el producto punto $a \cdot b$.
</div>

In [38]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

pesador = TfidfVectorizer(stop_words=["el", "la", "estaba", "venía"])
pesos = pesador.fit_transform(resenas)
print("Coseno con conteos:")
print(np.round(cosine_similarity(conteos), 2))
print("Coseno con TF-IDF:")
print(np.round(cosine_similarity(pesos), 2))

Coseno con conteos:
[[1.   0.41 0.  ]
 [0.41 1.   0.  ]
 [0.   0.   1.  ]]
Coseno con TF-IDF:
[[1.   0.29 0.  ]
 [0.29 1.   0.  ]
 [0.   0.   1.  ]]


Las dos primeras reseñas solo comparten `completo`. Con conteos su similitud es 0,41; con TF-IDF baja a 0,29, porque `completo` aparece en dos de las tres reseñas y pesa menos que `italiano`, `rico` o `frío`, que están en una sola.

### 3.1 — Predicción (0,1 puntos)

<!-- PREGUNTA -->
<div style="padding:16px 20px; margin:16px 0; border-left:4px solid #58a6ff; background:rgba(88,166,255,.12); color:inherit; border-radius:4px;">

  <strong style="display:block; margin-bottom:8px;">❓ Predicción</strong>
  En las descripciones de superherodb, palabras como <code>able</code>, <code>ability</code> o <code>strength</code> aparecen en cientos de personajes. La de Groot habla de árboles y madera.
  <ol>
  <li>¿Qué tipo de vecinos esperan para Groot si comparamos conteos?</li>
  <li>¿Y si comparamos TF-IDF?</li>
  </ol>
</div>

**1.** Con bag of words espero vecinos que repitan vocabulario general de habilidades, aunque sus poderes sean distintos.

**2.** TF-IDF debería dar más peso a palabras como `wood` y `trees` y recuperar personajes relacionados con plantas o que mencionen a Groot.

### 3.2 — TF-IDF sobre los poderes (0,3 puntos)

Trabajaremos solo con los personajes que tienen `powers_text` no vacío.

In [39]:
con_texto = features.filter(
    pl.col("powers_text").is_not_null()
    & (pl.col("powers_text").str.strip_chars() != "")
)
nombres_texto = con_texto["name"].to_list()
textos = con_texto["powers_text"].to_list()
print(f"Personajes con texto: {con_texto.height}")

Personajes con texto: 1033


Ajusten un `TfidfVectorizer` con `stop_words="english"`, `min_df=2` y `max_features=5000` sobre `textos`. `max_features=5000` conserva solo las 5 000 palabras más frecuentes del corpus; qué hace `min_df` lo discutirán en la pregunta 2. Guarden el vectorizador en `vectorizador` y la matriz en `tfidf`, y muestren su forma y la fracción de celdas distintas de 0 (hint: `nnz`).

In [40]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizador = TfidfVectorizer(
    stop_words="english", min_df=2, max_features=5000
)
tfidf = vectorizador.fit_transform(textos)
print("Forma:", tfidf.shape)
print(f"Fracción no nula: {tfidf.nnz / (tfidf.shape[0] * tfidf.shape[1]):.4%}")

Forma: (1033, 5000)
Fracción no nula: 1.7313%


In [41]:
texto_con_tokens = np.asarray(tfidf.getnnz(axis=1)).ravel() > 0
print("Sin tokens retenidos:")
print(con_texto.filter(pl.Series(~texto_con_tokens)).select("name"))
assert int((~texto_con_tokens).sum()) == 3

Sin tokens retenidos:
shape: (3, 1)
┌─────────────┐
│ name        │
│ ---         │
│ str         │
╞═════════════╡
│ General Vex │
│ Rock Lee    │
│ Splice      │
└─────────────┘


General Vex y Splice tienen el texto literal `"None"`; Rock Lee tiene `"Eight Gates"`, cuyos tokens desaparecen con `min_df=2`. Conservamos sus filas para no desalinear tablas y matrices, pero un vector cero no aporta evidencia de parecido textual. Los excluiremos del mapa UMAP, y en la representación combinada de la 5.4 solo aportarán sus puntajes, porque normalizar un vector cero no lo convierte en uno de norma 1.

Muestren las diez palabras con mayor peso TF-IDF en la descripción de Groot.

In [42]:
indice_groot = nombres_texto.index("Groot")
pesos_groot = tfidf[indice_groot].toarray().ravel()
orden = np.argsort(-pesos_groot)[:10]
pl.DataFrame({
    "palabra": vectorizador.get_feature_names_out()[orden],
    "peso_tfidf": pesos_groot[orden],
})

palabra,peso_tfidf
str,f64
"""groot""",0.818968
"""wood""",0.201506
"""trees""",0.163557
"""absorb""",0.095337
"""miniature""",0.081779
"""education""",0.081779
"""improvised""",0.079729
"""rebuild""",0.079729
"""quasi""",0.077953


<!-- PREGUNTA -->
<div style="padding:16px 20px; margin:16px 0; border-left:4px solid #58a6ff; background:rgba(88,166,255,.12); color:inherit; border-radius:4px;">

  <strong style="display:block; margin-bottom:8px;">❓ Preguntas</strong>
  <ol>
  <li>¿Qué fracción de la matriz es distinta de 0 y por qué se guarda como sparse matrix?</li>
  <li>¿Qué hace <code>min_df=2</code> y por qué conviene aquí? Piensen en un nombre propio que aparece en una sola descripción.</li>
  </ol>
</div>

**1.** Aproximadamente el 1,73 % de las celdas contiene un valor distinto de cero. Se guarda como matriz dispersa para no almacenar millones de ceros.

**2.** `min_df=2` elimina términos presentes en un solo documento. Evita muchas palabras aisladas, incluidos nombres propios poco repetidos, que podrían dar similitudes engañosas.

### 3.3 — Bag of words de los poderes (0,3 puntos)

Ajusten un `CountVectorizer` sobre `textos` con los mismos parámetros del `TfidfVectorizer` de la 3.2. Guarden el vectorizador en `contador_poderes` y la matriz en `bolsa`.

In [43]:
from sklearn.feature_extraction.text import CountVectorizer

contador_poderes = CountVectorizer(
    stop_words="english", min_df=2, max_features=5000
)
bolsa = contador_poderes.fit_transform(textos)
print("Forma:", bolsa.shape)

Forma: (1033, 5000)


Muestren las diez palabras más frecuentes de todo el corpus, con su conteo total y en cuántas descripciones aparecen.

In [44]:
conteos_corpus = np.asarray(bolsa.sum(axis=0)).ravel()
documentos_con_palabra = np.asarray((bolsa > 0).sum(axis=0)).ravel()
pl.DataFrame({
    "palabra": contador_poderes.get_feature_names_out(),
    "conteo": conteos_corpus,
    "documentos": documentos_con_palabra,
}).sort("conteo", descending=True).head(10)

palabra,conteo,documentos
str,i64,i64
"""able""",1718,458
"""ability""",990,383
"""energy""",935,284
"""body""",898,328
"""strength""",862,390
"""power""",834,332
"""powers""",827,359
"""human""",759,297
"""force""",729,216


Muestren las diez palabras con mayor conteo en la descripción de Groot.

In [45]:
conteos_groot = bolsa[indice_groot].toarray().ravel()
orden = np.argsort(-conteos_groot)[:10]
pl.DataFrame({
    "palabra": contador_poderes.get_feature_names_out()[orden],
    "conteo": conteos_groot[orden],
})

palabra,conteo
str,i64
"""groot""",9
"""wood""",3
"""strength""",2
"""trees""",2
"""able""",2
"""ability""",2
"""absorb""",2
"""control""",2
"""time""",1


<!-- PREGUNTA -->
<div style="padding:16px 20px; margin:16px 0; border-left:4px solid #58a6ff; background:rgba(88,166,255,.12); color:inherit; border-radius:4px;">

  <strong style="display:block; margin-bottom:8px;">❓ Preguntas</strong>
  <ol>
  <li>¿Qué tienen en común las diez palabras más frecuentes del corpus y por qué ayudan poco a distinguir a un personaje de otro?</li>
  <li>Comparen las palabras de Groot por conteo con las de mayor peso TF-IDF de la 3.2. ¿Cuáles se mantienen arriba, cuáles bajan y por qué?</li>
  </ol>
</div>

**1.** Predominan palabras generales como `able`, `ability`, `energy` y `strength`: son comunes a muchos personajes y distinguen poco.

**2.** En Groot, `groot` y `wood` siguen arriba; `trees` gana importancia en TF-IDF, mientras `able` y `ability` bajan por ser demasiado frecuentes.

### 3.4 — Dos pesos, dos vecindarios (0,3 puntos)

Muestren los cinco vecinos de Groot, Iron Man y Magneto con `metrica="cosine"`, sobre `bolsa` y sobre `tfidf`.

In [46]:
for personaje in ["Groot", "Iron Man", "Magneto"]:
    print(personaje)
    print("Bag of words")
    display(vecinos_mas_cercanos(bolsa, nombres_texto, personaje, metrica="cosine"))
    print("TF-IDF")
    display(vecinos_mas_cercanos(tfidf, nombres_texto, personaje, metrica="cosine"))

Groot
Bag of words


name,distancia
str,f64
"""Raven (Titans)""",0.826058
"""One Punch Man""",0.826995
"""Professor X (FOX)""",0.827765
"""Devilman""",0.83148
"""Husk""",0.83214


TF-IDF


name,distancia
str,f64
"""Star-Lord (Celestial Power MCU…",0.900826
"""Poison Ivy (Arkham)""",0.920168
"""Poison Ivy""",0.920497
"""Husk""",0.932937
"""Beast (FOX)""",0.936213


Iron Man
Bag of words


name,distancia
str,f64
"""Mr.Krabs""",0.553524
"""War Machine""",0.571418
"""Destroyer""",0.634224
"""Killian (MCU)""",0.643274
"""Iron Monger (MCU)""",0.696081


TF-IDF


name,distancia
str,f64
"""Mr.Krabs""",0.613985
"""War Machine""",0.642836
"""Killian (MCU)""",0.654942
"""Iron Monger (MCU)""",0.721191
"""Destroyer""",0.727755


Magneto
Bag of words


name,distancia
str,f64
"""Polaris""",0.483762
"""Onslaught""",0.597606
"""Cecilia Reyes""",0.730256
"""Cable""",0.737568
"""Supergirl""",0.754485


TF-IDF


name,distancia
str,f64
"""Polaris""",0.564434
"""Onslaught""",0.739482
"""Professor X (FOX)""",0.825273
"""Polaris (Fox)""",0.841304
"""Cecilia Reyes""",0.852183


<!-- PREGUNTA -->
<div style="padding:16px 20px; margin:16px 0; border-left:4px solid #58a6ff; background:rgba(88,166,255,.12); color:inherit; border-radius:4px;">

  <strong style="display:block; margin-bottom:8px;">❓ Preguntas</strong>
  <ol>
  <li>Para Groot, ¿qué comparten con él sus vecinos por bag of words y qué comparten sus vecinos TF-IDF? Citen dos nombres de cada lista.</li>
  <li>Mr.Krabs es el primer vecino de Iron Man en las dos representaciones. Propongan qué palabra de su descripción puede explicarlo y qué dice eso de comparar textos por sus palabras.</li>
  <li>¿Qué representación usarían para buscar equivalentes y qué riesgo tiene esa elección?</li>
  </ol>
</div>

**1.** Con conteos, Groot queda cerca de Raven (Titans) y One Punch Man, en parte por palabras generales. TF-IDF acerca Star-Lord (Celestial Power MCU) y Poison Ivy (Arkham), por referencias más específicas a Groot o a la naturaleza.

**2.** `armor` es la palabra compartida por Iron Man y Mr.Krabs. Muestra que coincidir en una palabra no asegura poderes ni funciones realmente similares.

**3.** Usaría TF-IDF porque reduce la influencia del vocabulario común. Aun así, puede dar demasiado peso a nombres y coincidencias de texto fuera de contexto.

### 3.5 — Trasladar la codificación de texto al módulo (0,2 puntos)

<!-- MODULARIZACIÓN -->
<div style="padding:16px 20px; margin:16px 0; border-left:4px solid #f0883e; background:rgba(240,136,62,.12); color:inherit; border-radius:4px;">

  <strong style="display:block; margin-bottom:8px;">🛠️ Modularización — Texto</strong>
  Implementen en <code>src/heroverse/text.py</code> la función <code>vectorizar_tfidf(textos, min_df, max_features)</code>, que devuelve el vectorizador ajustado y la matriz, y la función <code>vectorizar_bolsa(textos, min_df, max_features)</code>, que hace lo mismo con conteos. Las dos descartan las stop words del inglés, porque las descripciones están en inglés, y usan por omisión <code>min_df=2</code> y <code>max_features=5000</code>, los mismos valores de la 3.2.
</div>

In [47]:
from src.heroverse.text import vectorizar_bolsa, vectorizar_tfidf

_, tfidf_modulo = vectorizar_tfidf(textos)
tfidf_igual = (tfidf_modulo != tfidf).nnz == 0
print(f"TF-IDF del módulo igual al del notebook: {tfidf_igual}")

_, bolsa_modulo = vectorizar_bolsa(textos)
bolsa_igual = (bolsa_modulo != bolsa).nnz == 0
print(f"Bag of words del módulo igual al del notebook: {bolsa_igual}")

TF-IDF del módulo igual al del notebook: True
Bag of words del módulo igual al del notebook: True


<!-- COMPROBACIÓN -->
<div style="padding:16px 20px; margin:16px 0; border-left:4px solid #2da44e; background:rgba(45,164,78,.12); color:inherit; border-radius:4px;">

  <strong style="display:block; margin-bottom:8px;">🧪 Comprobación</strong>
  Ejecutar <code>uv run pytest -m etapa3</code>. La celda de arriba debe imprimir <code>True</code> dos veces.
</div>

---
## Etapa 4 — Mapas del catálogo (0,8 puntos)

<!-- LORE -->
<div style="padding:16px 20px; margin:16px 0; border-left:4px solid #0f9e99; background:rgba(15,158,153,.12); color:inherit; border-radius:4px;">

  <strong style="display:block; margin-bottom:8px;">📜 Un mapa para la reunión</strong>
  El viernes la Magneta presenta el avance a su socio, que no va a mirar tablas de 327 ni de 5 000 columnas. Pide «un mapa del catálogo», un gráfico donde se vea quién está cerca de quién. Un mapa así existe, pero deforma: el equipo tiene que saber qué se puede leer en él antes de que alguien tome una decisión mirándolo.
</div>

### 4.1 — PCA de los puntajes con loadings (0,4 puntos)

<!-- DEFINICIÓN -->
<div style="padding:16px 20px; margin:16px 0; border-left:4px solid #3fb950; background:rgba(63,185,80,.12); color:inherit; border-radius:4px;">

  <strong style="display:block; margin-bottom:8px;">📖 PCA y loadings</strong>
  El <strong>análisis de componentes principales</strong> (PCA) construye nuevos ejes, las <strong>componentes</strong>, que son combinaciones lineales de las features originales. La primera apunta hacia donde los datos varían más; cada una de las siguientes es perpendicular (ortogonal) a las anteriores y recoge la mayor variación que queda. <code>components_</code> contiene los coeficientes de cada combinación. La <strong>varianza explicada</strong> indica qué fracción de la varianza total, la suma de las varianzas de todas las features, recoge cada componente. Al conservar solo dos componentes, las distancias y vecindades pueden cambiar.

  Los <strong>loadings</strong> muestran cómo se relaciona cada variable original con las componentes. Se calculan multiplicando los coeficientes de cada componente por la raíz de su varianza. Con features estandarizadas, como nuestros puntajes, cada loading es aproximadamente la correlación entre la variable y la componente, así que queda entre −1 y 1. En un mapa se dibujan como flechas desde el origen: el signo indica la dirección de asociación y el valor absoluto, su intensidad en cada eje. Una flecha corta en este plano puede corresponder a una variable mejor representada por otras componentes. Los loadings ayudan a interpretar los ejes; no prueban que existan grupos.
</div>

Ajusten `pca_puntajes`, un `PCA` sobre las seis columnas de puntajes de `tabular`, ya imputadas y estandarizadas. La celda que sigue a la suya muestra la varianza explicada de las seis componentes.

In [48]:
from sklearn.decomposition import PCA

pca_puntajes = PCA().fit(tabular.select(PUNTAJES).to_numpy())

In [49]:
print(
    "Varianza explicada:", np.round(pca_puntajes.explained_variance_ratio_, 3)
)

Varianza explicada: [0.561 0.182 0.083 0.078 0.058 0.038]


Construyan un único mapa PCA de los 1 367 personajes, con PC1 y PC2, color por `creator` y `name` al pasar el cursor. Agreguen seis flechas con sus etiquetas y una tabla de loadings de las dos primeras componentes. Usen `components_.T * np.sqrt(explained_variance_)` y mantengan las flechas en esa escala, sin factores adicionales. Indiquen la varianza explicada en cada eje y usen la misma escala visual en ambos, para que una distancia horizontal y una vertical se lean igual (hint: `update_yaxes(scaleanchor="x")`). Las filas del mapa deben conservar el orden de `features`.

Hint: [la documentación de Plotly sobre PCA](https://plotly.com/python/pca-visualization/#visualize-loadings) muestra cómo añadir flechas con `add_annotation`, usando `axref="x"` y `ayref="y"` para que el origen y el extremo estén en coordenadas del gráfico.

In [50]:
proyeccion_pca = pca_puntajes.transform(tabular.select(PUNTAJES).to_numpy())
loadings = pca_puntajes.components_.T * np.sqrt(pca_puntajes.explained_variance_)
tabla_loadings = pl.DataFrame({
    "puntaje": PUNTAJES,
    "PC1": loadings[:, 0],
    "PC2": loadings[:, 1],
})
display(tabla_loadings)

mapa_pca = features.select("name", "creator").with_columns(
    pl.Series("PC1", proyeccion_pca[:, 0]),
    pl.Series("PC2", proyeccion_pca[:, 1]),
)
fig_pca = px.scatter(
    mapa_pca.to_pandas(), x="PC1", y="PC2", color="creator",
    hover_name="name", title="PCA de los puntajes",
)
for etiqueta, (x, y) in zip(PUNTAJES, loadings[:, :2]):
    fig_pca.add_annotation(
        x=float(x), y=float(y), ax=0, ay=0, axref="x", ayref="y",
        text=etiqueta, showarrow=True, arrowhead=3,
    )
fig_pca.update_xaxes(title=f"PC1 ({100 * pca_puntajes.explained_variance_ratio_[0]:.1f} %)")
fig_pca.update_yaxes(
    title=f"PC2 ({100 * pca_puntajes.explained_variance_ratio_[1]:.1f} %)",
    scaleanchor="x", scaleratio=1,
)
fig_pca.show()

puntaje,PC1,PC2
str,f64,f64
"""intelligence_score""",0.505931,0.727856
"""strength_score""",0.809145,-0.377125
"""speed_score""",0.835154,-0.153097
"""durability_score""",0.871223,-0.238973
"""power_score""",0.783088,-0.108027
"""combat_score""",0.621286,0.575511


<!-- COMPROBACIÓN -->
<div style="padding:16px 20px; margin:16px 0; border-left:4px solid #2da44e; background:rgba(45,164,78,.12); color:inherit; border-radius:4px;">

  <strong style="display:block; margin-bottom:8px;">🧪 Comprobación manual</strong>
  Debe aparecer un mapa con 1 367 observaciones y seis flechas etiquetadas desde el origen; la tabla tiene seis filas y dos columnas de loadings. PC1 y PC2 explican aproximadamente el 74,3 % de la varianza en conjunto.
</div>

<!-- PREGUNTA -->
<div style="padding:16px 20px; margin:16px 0; border-left:4px solid #58a6ff; background:rgba(88,166,255,.12); color:inherit; border-radius:4px;">

  <strong style="display:block; margin-bottom:8px;">❓ Preguntas</strong>
  <ol>
  <li>¿Cuántas componentes hacen falta para superar el 80 % de la varianza? ¿Qué limitación tiene el mapa de dos componentes?</li>
  <li>Interpreten PC1 y PC2 usando las flechas y la tabla. ¿Qué nombres les pondrían y qué variables sustentan esa elección?</li>
  </ol>
</div>

**1.** Se necesitan **3 componentes** para superar el 80 %. PC1 y PC2 explican cerca del **74,3 %**, así que el mapa pierde parte de la variación y puede distorsionar distancias.

**2.** PC1 parece un eje de **capacidad general**: fuerza, velocidad, resistencia y poder cargan positivamente. PC2 contrapone **inteligencia y combate** (cargas positivas) frente a fuerza y resistencia (negativas).

### 4.2 — UMAP del texto de poderes (0,4 puntos)

<!-- DEFINICIÓN -->
<div style="padding:16px 20px; margin:16px 0; border-left:4px solid #3fb950; background:rgba(63,185,80,.12); color:inherit; border-radius:4px;">

  <strong style="display:block; margin-bottom:8px;">📖 UMAP y otras técnicas</strong>
  <strong>UMAP</strong> conecta cada punto con sus <code>n_neighbors</code> vecinos más cercanos, formando un grafo de vecindades, y busca posiciones en dos dimensiones que mantengan esas conexiones. Valores pequeños de <code>n_neighbors</code> priorizan relaciones locales y valores mayores incorporan un contexto más amplio. A diferencia de PCA, sus ejes no son combinaciones de las features y no tienen interpretación. Es estocástico, es decir, usa azar, por lo que fijamos una semilla para reproducir el mapa.
</div>

<!-- WARNING -->
<div style="padding:16px 20px; margin:16px 0; border-left:4px solid #d29922; background:rgba(210,153,34,.12); color:inherit; border-radius:4px;">

  <strong style="display:block; margin-bottom:8px;">⚠️ Lo que el mapa no dice</strong>
  Llamamos <strong>isla</strong> a un grupo de puntos separado visualmente del resto. El área de una isla y la distancia entre islas en UMAP no miden directamente cuántos personajes hay ni qué tan distintos son en el espacio original. Una vecindad visual debe contrastarse con los vectores originales; una isla por sí sola no prueba que exista un grupo real en los datos. PCA usa puntajes y UMAP usa texto: las diferencias entre estos dos mapas dependen tanto de la representación como del método.
</div>

<!-- PREGUNTA -->
<div style="padding:16px 20px; margin:16px 0; border-left:4px solid #58a6ff; background:rgba(88,166,255,.12); color:inherit; border-radius:4px;">

  <strong style="display:block; margin-bottom:8px;">❓ Predicción antes de proyectar</strong>
  <ol>
  <li>Con los vecinos de texto de la etapa 3, ¿qué personajes esperan ver cerca en UMAP?</li>
  <li>¿Qué evidencia buscarían en sus descripciones para interpretar esa cercanía?</li>
  </ol>
</div>


**1.**  Usando a Groot como ejemplo, esperaría que aparezca cerca de personajes como Swamp Thing o Poison Ivy, por sus poderes relacionados con la naturaleza, más que de los Guardianes de la Galaxia, ya que TF-IDF compara descripciones y no equipos.

**2.** Comprobaría si los personajes cercanos comparten habilidades como regeneración o control de plantas, lo que explicaría su proximidad en UMAP.

Proyecten `tfidf[texto_con_tokens]` con `umap.UMAP(n_neighbors=15, metric="cosine", random_state=0)`. Construyan un único gráfico con `px.scatter`, color por `creator` y `name` al pasar el cursor. Apliquen el mismo arreglo booleano `texto_con_tokens` (la máscara) a `con_texto`: el mapa debe conservar el orden de sus 1 030 personajes y excluir los tres vectores cero. El paquete `umap-learn` se importa como `import umap`.

In [51]:
import umap

con_texto_umap = con_texto.filter(pl.Series(texto_con_tokens))
modelo_umap = umap.UMAP(n_neighbors=15, metric="cosine", random_state=0)
proyeccion_umap = modelo_umap.fit_transform(tfidf[texto_con_tokens])
mapa_umap = con_texto_umap.select("name", "creator").with_columns(
    pl.Series("UMAP1", proyeccion_umap[:, 0]),
    pl.Series("UMAP2", proyeccion_umap[:, 1]),
)
print("Personajes proyectados:", mapa_umap.height)
fig_umap = px.scatter(
    mapa_umap.to_pandas(), x="UMAP1", y="UMAP2", color="creator",
    hover_name="name", title="Poderes descritos: UMAP sobre TF-IDF",
)
fig_umap.show()

c:\Users\Asus\Laboratorio-de-Programaci-n-Cient-fica-para-Ciencia-de-DatosIA7202\labs\lab_8\.venv\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(


Personajes proyectados: 1030


<!-- COMPROBACIÓN -->
<div style="padding:16px 20px; margin:16px 0; border-left:4px solid #2da44e; background:rgba(45,164,78,.12); color:inherit; border-radius:4px;">

  <strong style="display:block; margin-bottom:8px;">🧪 Comprobación manual</strong>
  Debe aparecer un mapa UMAP con 1 030 observaciones. General Vex, Splice y Rock Lee no deben aparecer.
</div>

Busquen a Lloyd (The LEGO Ninjago Movie) en el mapa y anoten dos o tres de sus vecinos visuales. Muestren el `powers_text` de Lloyd y de esos vecinos para contrastar sus descripciones (hint: `features.filter(pl.col("name").is_in([...]))`).

In [52]:
lloyd = "Lloyd (The LEGO Ninjago Movie)"
nombres_umap = con_texto_umap["name"].to_list()
indice_lloyd = nombres_umap.index(lloyd)
distancias_umap = np.linalg.norm(
    proyeccion_umap - proyeccion_umap[indice_lloyd], axis=1
)
cercanos_umap = [i for i in np.argsort(distancias_umap) if i != indice_lloyd][:3]
vecinos_visuales = [nombres_umap[i] for i in cercanos_umap]
print("Vecinos visuales:", vecinos_visuales)
display(features.filter(
    pl.col("name").is_in([lloyd, *vecinos_visuales])
).select("name", "powers_text"))

Vecinos visuales: ['Samurai Mech(Stone Army)', 'Nya (Water Ninja)', 'Garmadon (The Lego Ninjago Movie)']


name,powers_text
str,str
"""Garmadon (The Lego Ninjago Mov…","""Garmadon uses a shark staff th…"
"""Lloyd (The LEGO Ninjago Movie)""","""Lloyd used a sword in the trai…"
"""Nya (Water Ninja)""","""When Nya became the Water Ninj…"
"""Samurai Mech(Stone Army)""","""The Samurai Mech was extremely…"


<!-- PREGUNTA -->
<div style="padding:16px 20px; margin:16px 0; border-left:4px solid #58a6ff; background:rgba(88,166,255,.12); color:inherit; border-radius:4px;">

  <strong style="display:block; margin-bottom:8px;">❓ Preguntas</strong>
  <ol>
  <li>El socio ve una isla grande y dice «este es el arquetipo más común». ¿Qué le responderían?</li>
  <li>¿Qué vecindad visual pudieron respaldar con las descripciones? ¿Qué límite tiene colorear por editorial para interpretar el parecido?</li>
  </ol>
</div>

**1.** Una isla grande de UMAP no prueba que haya un arquetipo frecuente: el algoritmo prioriza vecindades y distorsiona áreas y distancias entre grupos.

**2.** Las descripciones de Lloyd y otros personajes Ninjago permiten contrastar si la vecindad visual que muestra el código corresponde a armas y combate. El color por editorial ayuda a contextualizar, pero no demuestra similitud ni reemplaza la lectura del texto. *Los vecinos exactos se imprimen al ejecutar el mapa UMAP*.

---
## Etapa 5 — Arquetipos y equivalentes (1,0 puntos)

<!-- LORE -->
<div style="padding:16px 20px; margin:16px 0; border-left:4px solid #0f9e99; background:rgba(15,158,153,.12); color:inherit; border-radius:4px;">

  <strong style="display:block; margin-bottom:8px;">📜 El mazo</strong>
  El socio quedó convencido con el mapa, pero una isla no es una categoría del juego. La Magneta necesita para el lunes tres cosas: los arquetipos del mazo con un perfil que un diseñador entienda, a qué arquetipo pertenece cada uno de los 81 personajes nuevos, y los equivalentes no Marvel de Deadpool, Wolverine, Hulk, Iron Man y Magneto. Nadie le puede decir cuáles son los arquetipos correctos: no hay etiquetas. Hay que justificarlos con lo que muestran los datos.
</div>

<!-- DEFINICIÓN -->
<div style="padding:16px 20px; margin:16px 0; border-left:4px solid #3fb950; background:rgba(63,185,80,.12); color:inherit; border-radius:4px;">

  <strong style="display:block; margin-bottom:8px;">📖 Representación y agrupamiento</strong>

  La pregunta «¿aparecen grupos naturales?» tiene nombre: <strong>clustering</strong>. Un algoritmo de clustering recibe los vectores de features, sin ninguna etiqueta, y los reparte en grupos de modo que los puntos de un mismo grupo queden cerca entre sí. Su resultado depende de dos decisiones.

  Depende, primero, de la <strong>representación</strong>. El algoritmo agrupa puntos, no personajes: si cambiamos las features, cambian las posiciones, y con ellas los grupos. Con solo fuerza y velocidad, Superman y Hulk podrían caer juntos; si agregamos inteligencia, quizás ya no.

  Depende, además, del <strong>algoritmo</strong>, porque cada uno tiene su propia idea de qué es un grupo. En la figura, cada fila es un mismo conjunto de puntos y cada columna, un algoritmo distinto; el color indica el grupo asignado y el negro, los puntos que el algoritmo deja sin grupo. En la primera fila, K-Means corta los dos anillos por la mitad, porque busca grupos compactos alrededor de un centro, mientras que DBSCAN sigue las zonas densas y separa cada anillo. En la última, los puntos están repartidos al azar y no hay grupos, pero K-Means, Ward o Gaussian Mixture igual entregan tres.

  <div style="text-align: center; margin: 16px 0;">
    <img src="static/sphx_glr_plot_cluster_comparison_001.png" alt="Comparación de once algoritmos de clustering de scikit-learn sobre seis conjuntos de puntos en dos dimensiones: dos anillos concéntricos, dos medias lunas, tres grupos de distinta dispersión, tres grupos alargados, tres grupos redondos y puntos uniformes sin estructura. Cada algoritmo colorea los grupos que encuentra y los resultados difieren entre columnas." style="width: 900px; max-width: 100%; height: auto;">
    <br>
    <small>Fuente: documentación de scikit-learn, «Comparing different clustering algorithms on toy datasets».</small>
  </div>

  Que un algoritmo entregue grupos no significa que existan. Por eso, en esta etapa tendremos que justificar cada agrupación con evidencia.

  <br>
</div>

<!-- DEFINICIÓN -->
<div style="padding:16px 20px; margin:16px 0; border-left:4px solid #3fb950; background:rgba(63,185,80,.12); color:inherit; border-radius:4px;">

  <strong style="display:block; margin-bottom:8px;">📖 K-Means, inercia y método del codo</strong>
  <strong>K-Means</strong> reparte los puntos en $k$ grupos y busca los centros $\mu_1, \dots, \mu_k$ que minimizan la <strong>inercia</strong>, la suma de distancias al cuadrado de cada punto a su centro: $\sum_i \lVert x_i - \mu_{c(i)} \rVert^2$, donde $c(i)$ es el grupo asignado al punto $x_i$. Para lograrlo alterna dos pasos hasta que las asignaciones dejan de cambiar: asigna cada punto al centro más cercano y mueve cada centro al promedio de sus puntos.

  La inercia siempre baja al aumentar $k$; el <strong>método del codo</strong> busca el $k$ desde el cual deja de bajar mucho. K-Means parte de centros al azar, así que su resultado depende de la semilla. <code>n_init</code> indica cuántas veces parte desde centros distintos: con <code>n_init=10</code> se queda con la corrida de menor inercia, y con <code>n_init=1</code> queda expuesto a lo que salga de una sola semilla.
</div>

<!-- DEFINICIÓN -->
<div style="padding:16px 20px; margin:16px 0; border-left:4px solid #3fb950; background:rgba(63,185,80,.12); color:inherit; border-radius:4px;">

  <strong style="display:block; margin-bottom:8px;">📖 Silhouette y ARI</strong>
  Para un punto, sea $a$ su distancia media a los demás puntos de su grupo y $b$ la menor distancia media a los puntos de otro grupo. Su <strong>silhouette</strong> es $s = (b - a) / \max(a, b)$, entre −1 y 1; el coeficiente es el promedio sobre todos los puntos. Cerca de 1, los grupos están bien separados; cerca de 0, el punto está en la frontera entre dos grupos; negativo, quedaría mejor en otro grupo.

  El <strong>índice de Rand ajustado</strong> (ARI) compara dos particiones de los mismos puntos: vale 1 si coinciden aunque numeren los grupos distinto, y cerca de 0 si coinciden como lo harían al azar; puede ser negativo si coinciden menos que eso. Sirve para medir estabilidad (la misma representación con otra semilla) y acuerdo (dos representaciones distintas), sin usar ninguna etiqueta verdadera.
</div>

In [53]:
from sklearn.metrics import adjusted_rand_score

print(adjusted_rand_score([0, 0, 1, 1, 2, 2], [2, 2, 0, 0, 1, 1]))
print(adjusted_rand_score([0, 0, 1, 1, 2, 2], [0, 1, 2, 0, 1, 2]))

1.0
-0.25


### 5.1 — Un silhouette demasiado bueno (0,2 puntos)

Antes de agrupar, miremos el rango de algunas columnas de `tabular`: K-Means usa distancia euclidiana, así que hereda todo lo que decidimos al escalar.

In [54]:
tabular.select(*PUNTAJES[:2], *MEDIDAS, "poder_Flight").describe()

statistic,intelligence_score,strength_score,altura_cm,peso_kg,n_poderes,poder_Flight
str,f64,f64,f64,f64,f64,f64
"""count""",1367.0,1367.0,1367.0,1367.0,1367.0,1367.0
"""null_count""",0.0,0.0,0.0,0.0,0.0,0.0
"""mean""",4.9899e-16,-6.2374e-17,0.15204,0.433876,-0.051423,0.259693
"""std""",1.000366,1.000366,7.155458,3.501887,0.83243,0.438626
"""min""",-4.636591,-1.217373,-57.161855,-14.678343,-2.080279,0.0
"""25%""",-0.443907,-0.919005,-0.591407,-0.531332,-0.525849,0.0
"""50%""",0.115117,-0.322268,0.0,0.0,0.0,0.0
"""75%""",0.674142,0.722021,0.408593,0.468668,0.474151,1.0
"""max""",0.953654,1.766309,62.701819,55.829276,2.115407,1.0


<!-- PREGUNTA -->
<div style="padding:16px 20px; margin:16px 0; border-left:4px solid #58a6ff; background:rgba(88,166,255,.12); color:inherit; border-radius:4px;">

  <strong style="display:block; margin-bottom:8px;">❓ Predicción antes de agrupar</strong>
  Con estos rangos:
  <ol>
  <li>¿Qué columnas esperan que decidan los grupos de K-Means sobre <code>tabular</code> completo?</li>
  <li>¿Qué tipo de personajes quedarán en un grupo aparte?</li>
  </ol>
</div>

**1.** Las medidas con valores extremos, especialmente `altura_cm` y `peso_kg`, podrían influir más que los seis puntajes en la formación de los grupos.

**2.** Espero que aparezca algún grupo pequeño de personajes con medidas muy atípicas, que podrían deberse a errores del scrape y no representar un arquetipo útil.

Para `k` entre 2 y 8, ajusten `KMeans(n_clusters=k, n_init=10, random_state=0)` sobre `tabular` completo y guarden en `tabla_k_completa` un DataFrame con `k`, `inercia` y `silhouette`.

In [55]:
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

X_tabular = tabular.to_numpy()
filas_k = []
for k in range(2, 9):
    modelo = KMeans(n_clusters=k, n_init=10, random_state=0)
    grupos = modelo.fit_predict(X_tabular)
    filas_k.append({
        "k": k,
        "inercia": float(modelo.inertia_),
        "silhouette": float(silhouette_score(X_tabular, grupos)),
    })
tabla_k_completa = pl.DataFrame(filas_k)
display(tabla_k_completa)

k,inercia,silhouette
i64,f64,f64
2,80449.508174,0.857464
3,50296.997103,0.818791
4,43877.857495,0.393111
5,39521.992737,0.222334
6,35637.573106,0.17787
7,33486.014467,0.179894
8,31416.754939,0.181106


In [56]:
from sklearn.cluster import KMeans

print(tabla_k_completa)
grupos_k2 = KMeans(n_clusters=2, n_init=10, random_state=0).fit_predict(
    X_tabular
)
print("Tamaños con k=2:", np.bincount(grupos_k2))
pequeno = int(np.argmin(np.bincount(grupos_k2)))
features.filter(pl.Series(grupos_k2 == pequeno)).select(
    "name", "creator", "altura_cm", "peso_kg"
)

shape: (7, 3)
┌─────┬──────────────┬────────────┐
│ k   ┆ inercia      ┆ silhouette │
│ --- ┆ ---          ┆ ---        │
│ i64 ┆ f64          ┆ f64        │
╞═════╪══════════════╪════════════╡
│ 2   ┆ 80449.508174 ┆ 0.857464   │
│ 3   ┆ 50296.997103 ┆ 0.818791   │
│ 4   ┆ 43877.857495 ┆ 0.393111   │
│ 5   ┆ 39521.992737 ┆ 0.222334   │
│ 6   ┆ 35637.573106 ┆ 0.17787    │
│ 7   ┆ 33486.014467 ┆ 0.179894   │
│ 8   ┆ 31416.754939 ┆ 0.181106   │
└─────┴──────────────┴────────────┘
Tamaños con k=2: [  11 1356]


name,creator,altura_cm,peso_kg
str,str,f64,f64
"""Aquagirl I""","""DC Comics""",3.0,118.0
"""Batman (LEGO)""","""Lego""",3.0,1.0
"""Black Spider""","""DC Comics""",3.0,171.0
"""Brickster""","""Lego""",10.0,11.0
"""General Kozu""","""Lego""",3.0,119.0
…,…,…,…
"""Lloyd (The LEGO Ninjago Movie)""","""Lego""",3.0,3.0
"""Mad Harriet""","""DC Comics""",3.0,145.0
"""Mr.Krabs""",null,13.0,3.0


<!-- PREGUNTA -->
<div style="padding:16px 20px; margin:16px 0; border-left:4px solid #58a6ff; background:rgba(88,166,255,.12); color:inherit; border-radius:4px;">

  <strong style="display:block; margin-bottom:8px;">❓ Preguntas</strong>
  <ol>
  <li>¿Qué valor de <code>k</code> tiene el mejor silhouette, qué tamaño tiene cada grupo y qué comparten los personajes del grupo pequeño?</li>
  <li>¿Por qué ese silhouette alto no es un buen arquetipo para el mazo? Expliquen qué feature lo produce y por qué el escalamiento robusto lo amplifica.</li>
  <li>Miren la columna <code>inercia</code>. ¿Dónde está el codo y coincide con el <code>k</code> de mejor silhouette? ¿Por qué ninguno de los dos criterios corrige el problema de la pregunta 2?</li>
  </ol>
</div>

**1.** Con `k=2` aparece el mejor silhouette (≈0,858), pero separa solo **11** personajes de los otros **1.356**. La mayoría de esos 11 tiene alturas registradas de 3 cm; no es un perfil jugable.

**2.** `log1p` comprime la cola alta, pero alturas muy pequeñas quedan muchas unidades por debajo de la mediana tras `RobustScaler`, porque el IQR de altura es estrecho. K-Means aísla esa rareza.

**3.** La mayor reducción de inercia ocurre hasta alrededor de `k=3`; no coincide con el máximo silhouette en `k=2`. Ninguna métrica distingue por sí sola estructura útil de errores o extremos.

### 5.2 — Arquetipos a partir de los puntajes (0,3 puntos)

Guarden en `X_puntajes` las seis columnas de puntajes de `tabular` como arreglo. Para cada `k` entre 2 y 6, construyan una fila de `tabla_k_puntajes` con las columnas `k`, `silhouette` y `estabilidad`:

- [ ] `silhouette`: el de `KMeans(n_clusters=k, n_init=10, random_state=0)` sobre `X_puntajes`, igual que en la 5.1;
- [ ] `estabilidad`: ajusten K-Means con `n_init=1` y las semillas 0 a 4, y promedien el ARI entre los 10 pares de particiones (hint: `itertools.combinations`).

In [57]:
from itertools import combinations
from sklearn.metrics import adjusted_rand_score

X_puntajes = tabular.select(PUNTAJES).to_numpy()
filas_puntajes = []
for k in range(2, 7):
    modelo = KMeans(n_clusters=k, n_init=10, random_state=0)
    etiquetas = modelo.fit_predict(X_puntajes)
    semillas = [
        KMeans(n_clusters=k, n_init=1, random_state=s).fit_predict(X_puntajes)
        for s in range(5)
    ]
    acuerdo = np.mean([
        adjusted_rand_score(a, b) for a, b in combinations(semillas, 2)
    ])
    filas_puntajes.append({
        "k": k,
        "silhouette": float(silhouette_score(X_puntajes, etiquetas)),
        "estabilidad": float(acuerdo),
    })
tabla_k_puntajes = pl.DataFrame(filas_puntajes)
display(tabla_k_puntajes)

k,silhouette,estabilidad
i64,f64,f64
2,0.311833,0.804961
3,0.314161,0.916037
4,0.270826,0.922207
5,0.259255,0.76991
6,0.265926,0.820507


En la pregunta 1 dirán qué `k` elegirían ustedes. Para lo que sigue del laboratorio usaremos `k=4`, que aísla un grupo que conviene revisar: ajusten `arquetipos = KMeans(n_clusters=4, n_init=10, random_state=0)` sobre `X_puntajes`.

In [58]:
arquetipos = KMeans(n_clusters=4, n_init=10, random_state=0)
arquetipos.fit(X_puntajes)

,"n_clusters n_clusters: int, default=8The number of clusters to form as well as the number ofcentroids to generate.For an example of how to choose an optimal value for `n_clusters` refer to:ref:`sphx_glr_auto_examples_cluster_plot_kmeans_silhouette_analysis.py`.",4
,"n_init n_init: 'auto' or int, default='auto'Number of times the k-means algorithm is run with different centroidseeds. The final results is the best output of `n_init` consecutive runsin terms of inertia. Several runs are recommended for sparsehigh-dimensional problems (see :ref:`kmeans_sparse_high_dim`).When `n_init='auto'`, the number of runs depends on the value of init:10 if using `init='random'` or `init` is a callable;1 if using `init='k-means++'` or `init` is an array-like... versionadded:: 1.2 Added 'auto' option for `n_init`... versionchanged:: 1.4 Default value for `n_init` changed to `'auto'`.",10
,"random_state random_state: int, RandomState instance or None, default=NoneDetermines random number generation for centroid initialization. Usean int to make the randomness deterministic.See :term:`Glossary <random_state>`.",0
,"init init: {'k-means++', 'random'}, callable or array-like of shape (n_clusters, n_features), default='k-means++'Method for initialization:* 'k-means++' : selects initial cluster centroids using sampling based on an empirical probability distribution of the points' contribution to the overall inertia. This technique speeds up convergence. The algorithm implemented is ""greedy k-means++"". It differs from the vanilla k-means++ by making several trials at each sampling step and choosing the best centroid among them.* 'random': choose `n_clusters` observations (rows) at random from data for the initial centroids.* If an array is passed, it should be of shape (n_clusters, n_features) and gives the initial centers.* If a callable is passed, it should take arguments X, n_clusters and a random state and return an initialization.For an example of how to use the different `init` strategies, see:ref:`sphx_glr_auto_examples_cluster_plot_kmeans_digits.py`.For an evaluation of the impact of initialization, see the example:ref:`sphx_glr_auto_examples_cluster_plot_kmeans_stability_low_dim_dense.py`.",'k-means++'
,"max_iter max_iter: int, default=300Maximum number of iterations of the k-means algorithm for asingle run.",300
,"tol tol: float, default=1e-4Relative tolerance with regards to Frobenius norm of the differencein the cluster centers of two consecutive iterations to declareconvergence.",0.0001
,"verbose verbose: int, default=0Verbosity mode.",0
,"copy_x copy_x: bool, default=TrueWhen pre-computing distances it is more numerically accurate to centerthe data first. If copy_x is True (default), then the original data isnot modified. If False, the original data is modified, and put backbefore the function returns, but small numerical differences may beintroduced by subtracting and then adding the data mean. Note that ifthe original data is not C-contiguous, a copy will be made even ifcopy_x is False. If the original data is sparse, but not in CSR format,a copy will be made even if copy_x is False.",True
,"algorithm algorithm: {""lloyd"", ""elkan""}, default=""lloyd""K-means algorithm to use. The classical EM-style algorithm is `""lloyd""`.The `""elkan""` variation can be more efficient on some datasets withwell-defined clusters, by using the triangle inequality. However it'smore memory intensive due to the allocation of an extra array of shape`(n_samples, n_clusters)`... versionchanged:: 0.18 Added Elkan algorithm.. versionchanged:: 1.1 Renamed ""full"" to ""lloyd"", and deprecated ""auto"" and ""full"". Changed ""auto"" to use ""lloyd"" instead of ""elkan"".",'lloyd'
Name,Type,Value
"cluster_centers_ cluster_centers_: ndarray of shape (n_clusters, n_features)Coordinates of cluster centers. If the algorithm stops before fullyconverging (see ``tol`` and ``max_iter``), these will not beconsistent with ``labels_``.","ndarray[float64](4, 6)","[[ 0.1

La celda siguiente muestra la tabla de `k` y el perfil de cada arquetipo, con los puntajes en su escala original de `features`.

In [59]:
print(tabla_k_puntajes)
(
    features.with_columns(pl.Series("arquetipo", arquetipos.labels_))
    .group_by("arquetipo")
    .agg(pl.len().alias("n"), pl.col(*PUNTAJES, "n_poderes").mean().round(0))
    .sort("arquetipo")
)

shape: (5, 3)
┌─────┬────────────┬─────────────┐
│ k   ┆ silhouette ┆ estabilidad │
│ --- ┆ ---        ┆ ---         │
│ i64 ┆ f64        ┆ f64         │
╞═════╪════════════╪═════════════╡
│ 2   ┆ 0.311833   ┆ 0.804961    │
│ 3   ┆ 0.314161   ┆ 0.916037    │
│ 4   ┆ 0.270826   ┆ 0.922207    │
│ 5   ┆ 0.259255   ┆ 0.76991     │
│ 6   ┆ 0.265926   ┆ 0.820507    │
└─────┴────────────┴─────────────┘


arquetipo,n,intelligence_score,strength_score,speed_score,durability_score,power_score,combat_score,n_poderes
i32,u32,f64,f64,f64,f64,f64,f64,f64
0,585,86.0,30.0,45.0,59.0,77.0,79.0,12.0
1,387,87.0,85.0,78.0,90.0,96.0,82.0,28.0
2,357,83.0,15.0,26.0,31.0,39.0,58.0,5.0
3,38,1.0,1.0,1.0,1.0,17.0,0.0,4.0


`alignment` y `creator` no participaron en el agrupamiento. Sirven para describir cada arquetipo, no para decidir si está bien formado:

In [60]:
por_arquetipo = features.with_columns(
    pl.Series("arquetipo", arquetipos.labels_),
    pl.col("creator").fill_null("desconocido"),
)
print(
    por_arquetipo.pivot(
        on="alignment",
        index="arquetipo",
        values="name",
        aggregate_function="len",
    ).sort("arquetipo")
)
por_arquetipo.filter(
    pl.col("creator").is_in(["Marvel Comics", "DC Comics"])
).pivot(
    on="creator", index="arquetipo", values="name", aggregate_function="len"
).sort("arquetipo")

shape: (4, 4)
┌───────────┬──────┬─────┬─────────┐
│ arquetipo ┆ Good ┆ Bad ┆ Neutral │
│ ---       ┆ ---  ┆ --- ┆ ---     │
│ i32       ┆ u32  ┆ u32 ┆ u32     │
╞═══════════╪══════╪═════╪═════════╡
│ 0         ┆ 350  ┆ 186 ┆ 49      │
│ 1         ┆ 199  ┆ 138 ┆ 50      │
│ 2         ┆ 223  ┆ 109 ┆ 25      │
│ 3         ┆ 22   ┆ 16  ┆ 0       │
└───────────┴──────┴─────┴─────────┘


arquetipo,Marvel Comics,DC Comics
i32,u32,u32
0,262,152
1,133,147
2,156,126
3,17,3


<!-- PREGUNTA -->
<div style="padding:16px 20px; margin:16px 0; border-left:4px solid #58a6ff; background:rgba(88,166,255,.12); color:inherit; border-radius:4px;">

  <strong style="display:block; margin-bottom:8px;">❓ Preguntas</strong>
  <ol>
  <li>¿Qué <code>k</code> elegirían ustedes y cómo se compara con <code>k=4</code>? Justifiquen con silhouette y estabilidad a la vez, y expliquen por qué ninguno de los dos basta solo.</li>
  <li>Pónganle nombre a cada arquetipo a partir de su perfil, como se lo presentarían a la Magneta.</li>
  <li>Uno de los grupos tiene puntajes cercanos a 0 en casi todo. ¿Es un arquetipo del juego o un rastro de los datos? Relaciónenlo con lo que decidieron en la 1.2 sobre los ceros de las fichas parciales.</li>
  </ol>
</div>

**1.** Elegiría **k=3**: tiene el mayor silhouette de puntajes (≈0,314) y buena estabilidad (≈0,916). En `k=4` el silhouette baja (≈0,271), aunque la estabilidad es algo mayor (≈0,922). Ambas métricas necesitan interpretación.

**2.** Con `k=4` llamaría a los grupos: **0, estrategas equilibrados**; **1, potencias completas**; **2, especialistas moderados**; **3, fichas sospechosamente bajas**.

**3.** El grupo 3 tiene casi todos los puntajes cerca de cero. Como en la etapa 1 solo anulamos fichas con *seis* ceros simultáneos, las fichas parciales con varios ceros quedaron registradas. No lo interpretaría automáticamente como un arquetipo real.

### 5.3 — Acuerdo entre representaciones (0,2 puntos)


Para los personajes de `con_texto`, ajusten K-Means con `k=4` sobre sus puntajes y sobre `tfidf`, y calculen el ARI entre ambas particiones. Conserven exactamente los mismos personajes y su orden, porque el ARI compara asignaciones de las mismas observaciones. Las tres filas de `tfidf` en cero se mantienen, aunque el grupo que reciban no dice nada sobre su texto.

In [61]:
indices_texto = [nombres.index(nombre) for nombre in nombres_texto]
puntajes_con_texto = X_puntajes[indices_texto]
etiquetas_puntajes = KMeans(
    n_clusters=4, n_init=10, random_state=0
).fit_predict(puntajes_con_texto)
etiquetas_texto = KMeans(
    n_clusters=4, n_init=10, random_state=0
).fit_predict(tfidf)
ari_representaciones = adjusted_rand_score(etiquetas_puntajes, etiquetas_texto)
print(f"ARI entre puntajes y texto: {ari_representaciones:.4f}")

ARI entre puntajes y texto: 0.0350


<!-- PREGUNTA -->
<div style="padding:16px 20px; margin:16px 0; border-left:4px solid #58a6ff; background:rgba(88,166,255,.12); color:inherit; border-radius:4px;">

  <strong style="display:block; margin-bottom:8px;">❓ Preguntas</strong>
  <ol>
  <li>¿Qué ARI obtuvieron entre texto y puntajes? ¿Significa que una de las dos representaciones está mal?</li>
  </ol>
</div>

El **ARI es aproximadamente 0,035**, muy próximo a cero. Los grupos de texto y los de puntajes casi no coinciden, pero eso no implica un error: representan aspectos diferentes de los personajes y K-Means depende de las variables usadas.

### 5.4 — Trasladar el clustering al módulo y entregar (0,3 puntos)

<!-- MODULARIZACIÓN -->
<div style="padding:16px 20px; margin:16px 0; border-left:4px solid #f0883e; background:rgba(240,136,62,.12); color:inherit; border-radius:4px;">

  <strong style="display:block; margin-bottom:8px;">🛠️ Modularización — Clustering y equivalentes</strong>
  Implementen en <code>src/heroverse/clustering.py</code> las funciones <code>elegir_k(X, ks, semilla)</code>, <code>estabilidad(X, k, semillas)</code> y <code>perfil_clusters(features, etiquetas, columnas)</code>, que trasladan lo que hicieron en 5.1 y 5.2: <code>elegir_k</code> devuelve un DataFrame con <code>k</code>, <code>inercia</code> y <code>silhouette</code>; <code>estabilidad</code>, el ARI promedio entre pares de semillas, y <code>perfil_clusters</code>, una fila por grupo con su tamaño y el promedio de <code>columnas</code>. Implementen también <code>equivalentes(X, personajes, consulta, k, excluir_creator, metrica)</code>, que devuelve los <code>k</code> personajes más cercanos que no son de <code>excluir_creator</code>; <code>personajes</code> es un DataFrame con <code>name</code> y <code>creator</code> en el orden de las filas de <code>X</code>, y los valores por omisión son <code>k=5</code>, <code>excluir_creator="Marvel Comics"</code> y <code>metrica="cosine"</code>. El contrato completo de cada función está en su docstring. Un <code>creator</code> nulo no se excluye: no hay evidencia de que sea de esa editorial, pero tampoco confirma que sea de otra. Una recomendación con editorial desconocida requiere verificarla.
</div>

In [62]:
from src.heroverse.clustering import (
    elegir_k,
    equivalentes,
    estabilidad,
    perfil_clusters,
)

print(elegir_k(X_puntajes, [3, 4, 5]))
print(f"Estabilidad con k=4: {estabilidad(X_puntajes, 4, list(range(5))):.2f}")
perfil_clusters(features, arquetipos.labels_, PUNTAJES)

shape: (3, 3)
┌─────┬─────────────┬────────────┐
│ k   ┆ inercia     ┆ silhouette │
│ --- ┆ ---         ┆ ---        │
│ i64 ┆ f64         ┆ f64        │
╞═════╪═════════════╪════════════╡
│ 3   ┆ 4118.495268 ┆ 0.314161   │
│ 4   ┆ 3305.337774 ┆ 0.270826   │
│ 5   ┆ 2891.674292 ┆ 0.259255   │
└─────┴─────────────┴────────────┘
Estabilidad con k=4: 0.92


cluster,n,intelligence_score,strength_score,speed_score,durability_score,power_score,combat_score
i32,u32,f64,f64,f64,f64,f64,f64
0,585,85.740385,30.240385,45.144231,58.730769,76.817308,78.682692
1,387,86.847545,84.793282,78.462532,90.439276,95.930233,81.640827
2,357,82.955182,14.747899,26.470588,31.008403,38.921569,57.54902
3,38,1.184211,0.526316,0.526316,1.315789,17.105263,0.131579


Para el entregable, los arquetipos de los personajes nuevos se predicen con el K-Means ya ajustado, sin reajustarlo.

Los equivalentes se buscan en una representación que junta dos bloques por personaje $i$: $t_i$, su fila TF-IDF, que tiene norma 1 si conserva tokens, y $s_i$, sus puntajes normalizados en la 1.6 (`puntajes_unitarios_catalogo`), multiplicados por 0,5. El texto aporta los poderes descritos y los puntajes, en qué se destaca el personaje.

¿Por qué 0,5? Es una elección de diseño. Como el coseno multiplica los vectores entre sí, el peso aparece al cuadrado: para dos personajes con ambos bloques de norma 1, el producto punto combinado es $t_i \cdot t_j + 0{,}25\, s_i \cdot s_j$, y la similitud coseno divide esa suma por $1 + 0{,}25 = 1{,}25$. El texto pesa entonces cuatro veces más que los puntajes en esa suma, aunque cuánto aporta cada bloque depende de cada par.

Dos límites: si el texto de un personaje es un vector cero, solo aporta su bloque de puntajes; y 0,5 no es un «50 % de importancia» ni garantiza equivalentes válidos. Como `tfidf` es una sparse matrix, los dos bloques se unen con `hstack` de `scipy.sparse`, no con el de NumPy.

In [63]:
from scipy.sparse import csr_matrix, hstack

nuevos_arquetipos = arquetipos.predict(
    nuevos_tabular.select(PUNTAJES).to_numpy()
)
print("Nuevos por arquetipo:", np.bincount(nuevos_arquetipos))

puntajes_unitarios = puntajes_unitarios_catalogo[
    features["name"].is_in(nombres_texto).to_numpy()
]
representacion_juego = hstack(
    [tfidf, csr_matrix(0.5 * puntajes_unitarios)]
).tocsr()
base = con_texto.select("name", "creator")
for favorito in ["Deadpool", "Wolverine", "Hulk", "Iron Man", "Magneto"]:
    print(
        favorito, equivalentes(representacion_juego, base, favorito, k=3).rows()
    )

Nuevos por arquetipo: [38 24 19]
Deadpool [('Grifter', 'DC Comics', 0.7519704837439802), ('Deathstroke (Injustice)', 'DC Comics', 0.7663106848651966), ('Hellboy', 'Dark Horse Comics', 0.7740494052285453)]
Wolverine [('Predator', 'Dark Horse Comics', 0.7552889277754535), ('Animal Man', 'DC Comics', 0.7699716411900894), ('Deathstroke (Injustice)', 'DC Comics', 0.7797167079369876)]
Hulk [('Rock Lee', 'Shueisha', 0.655872103777353), ('Asura', 'Capcom', 0.7390940846710858), ('One Punch Man', 'Shueisha', 0.7509513410350939)]
Iron Man [('Steel', 'DC Comics', 0.7049818852788218), ('Mr.Krabs', None, 0.7092391590756999), ('Battle-Suit Batman (DCEU)', 'DC Comics', 0.7786238148769781)]
Magneto [('Dr Manhattan', 'DC Comics', 0.7692749659718696), ('Rock Lee', 'Shueisha', 0.7773872461091944), ('T-X', 'Dark Horse Comics', 0.7784566913845647)]


Para el favorito que elijan en la pregunta siguiente, muestren su arquetipo y el de sus equivalentes, junto con sus puntajes y su `powers_text` (hint: `arquetipos.labels_` sigue el orden de `features`).

In [64]:
favorito = "Deadpool"
candidatos = equivalentes(representacion_juego, base, favorito, k=3)
display(candidatos)
display(
    features.with_columns(pl.Series("arquetipo", arquetipos.labels_))
    .filter(pl.col("name").is_in([favorito, *candidatos["name"].to_list()]))
    .select("name", "arquetipo", *PUNTAJES, "powers_text")
)

name,creator,distancia
str,str,f64
"""Grifter""","""DC Comics""",0.75197
"""Deathstroke (Injustice)""","""DC Comics""",0.766311
"""Hellboy""","""Dark Horse Comics""",0.774049


name,arquetipo,intelligence_score,strength_score,speed_score,durability_score,power_score,combat_score,powers_text
str,i32,i64,i64,i64,i64,i64,i64,str
"""Deadpool""",0,80,20,50,100,100,100,""" Deadpool possesses a superhu…"
"""Deathstroke (Injustice)""",0,90,30,35,70,100,100,"""Deathstroke is a metahuman, wh…"
"""Grifter""",0,75,15,50,80,100,95,"""Telepathy Sensory Scrying Min…"
"""Hellboy""",1,75,55,50,100,100,100,"""Hellboy's superhuman abilities…"


<!-- PREGUNTA -->
<div style="padding:16px 20px; margin:16px 0; border-left:4px solid #58a6ff; background:rgba(88,166,255,.12); color:inherit; border-radius:4px;">

  <strong style="display:block; margin-bottom:8px;">❓ Preguntas</strong>
  Elijan uno de los cinco favoritos y evalúen sus equivalentes; la cercanía numérica sola no basta.
  <ol>
  <li>¿Cuál le recomendarían a la Magneta? Usen al menos dos evidencias entre poderes compartidos, similitud de puntajes y arquetipo, y mencionen una limitación de las descripciones.</li>
  <li>Mencionen un equivalente que no les convenza y qué parte de la representación puede explicarlo.</li>
  </ol>
</div>

**1.** Para Deadpool recomendaría **Deathstroke (Injustice)**. Comparten curación acelerada, agilidad, puntería y combate alto (100 en ambos), aunque Deathstroke tiene menor resistencia (70 frente a 100). La descripción textual no refleja todas las mecánicas del juego.

**2.** **Grifter** sale todavía más cerca por coseno, pero sus facultades de telepatía y control mental cambian mucho su perfil. Esa coincidencia refleja vocabulario de habilidades y puntajes parecidos, no una equivalencia perfecta.

<!-- COMPROBACIÓN -->
<div style="padding:16px 20px; margin:16px 0; border-left:4px solid #2da44e; background:rgba(45,164,78,.12); color:inherit; border-radius:4px;">

  <strong style="display:block; margin-bottom:8px;">🧪 Comprobación</strong>
  Ejecutar <code>uv run pytest -m etapa5</code>. En la celda de arriba, ningún equivalente puede tener <code>creator == "Marvel Comics"</code>, y la suma de los nuevos por arquetipo debe ser 81.
</div>

### Extensiones opcionales — Año de aparición y DBSCAN

Estas extensiones no suman puntos ni agregan entregables. `anio_aparicion` se entrega implementada en `features.py`: pueden inspeccionar sus 394 valores disponibles y discutir si incluirla ayudaría al encargo. El preprocesador la descarta porque faltan 973 años; no tienen que desarrollar su extracción.

**DBSCAN** conecta regiones densas. Un punto es núcleo si tiene al menos `min_samples` puntos a distancia menor o igual que `eps`, incluyéndose a sí mismo. Un punto frontera está a distancia menor o igual que `eps` de un núcleo, pero no alcanza ese mínimo; los restantes son ruido, con etiqueta −1. No se fija `k`. El ejemplo provisto permite inspeccionar puntajes atípicos; sus parámetros no son universales y una etiqueta de ruido no prueba un error en la fuente.

In [65]:
from sklearn.cluster import DBSCAN

ruido = DBSCAN(eps=1.0, min_samples=5).fit(X_puntajes).labels_ == -1
print(f"Personajes como ruido: {int(ruido.sum())}")
features.filter(pl.Series(ruido)).select("name", *PUNTAJES).head(10)

Personajes como ruido: 69


name,intelligence_score,strength_score,speed_score,durability_score,power_score,combat_score
str,i64,i64,i64,i64,i64,i64
"""Anacondrai Serpent""",35,75,70,70,100,45
"""Annihilus""",90,80,45,55,60,65
"""Arkade""",50,20,40,45,100,95
"""Bantam""",65,55,25,55,20,55
"""Bathound""",50,10,15,30,30,35
"""Black Flash""",75,10,100,80,100,30
"""Bling!""",85,15,10,90,50,30
"""Blob""",55,85,25,95,30,70
"""Bolobo""",40,65,30,60,100,70


---

¡Listo! La Magneta ya tiene arquetipos, un lugar para cada carta nueva y equivalentes para sus cinco favoritos, para negociar sin pagar la licencia de Marvel. Las dudas se resuelven en el foro del curso en U-Cursos, y la entrega, con la Pull Request abierta, vence el domingo siguiente a esta sesión a las 23:59.